/**
 *
 *  Credits.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Credits.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string Credits::Cols::_id = "id";
const std::string Credits::Cols::_credit_type_id = "credit_type_id";
const std::string Credits::Cols::_person_id = "person_id";
const std::string Credits::Cols::_origin = "origin";
const std::string Credits::Cols::_external_id = "external_id";
const std::string Credits::primaryKeyName = "id";
const bool Credits::hasPrimaryKey = true;
const std::string Credits::tableName = "credits";

const std::vector<typename Credits::MetaData> Credits::metaData_={
{"id","int64_t","integer",8,1,1,1},
{"credit_type_id","int64_t","integer",8,0,0,1},
{"person_id","int64_t","integer",8,0,0,1},
{"origin","int64_t","integer",8,0,0,1},
{"external_id","std::string","text",0,0,0,1}
};
const std::string &Credits::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Credits::Credits(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["credit_type_id"].isNull())
        {
            creditTypeId_=std::make_shared<int64_t>(r["credit_type_id"].as<int64_t>());
        }
        if(!r["person_id"].isNull())
        {
            personId_=std::make_shared<int64_t>(r["person_id"].as<int64_t>());
        }
        if(!r["origin"].isNull())
        {
            origin_=std::make_shared<int64_t>(r["origin"].as<int64_t>());
        }
        if(!r["external_id"].isNull())
        {
            externalId_=std::make_shared<std::string>(r["external_id"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 5 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            creditTypeId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            personId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            origin_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            externalId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Credits::Credits(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            creditTypeId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            personId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            origin_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            externalId_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
}

Credits::Credits(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("credit_type_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["credit_type_id"].isNull())
        {
            creditTypeId_=std::make_shared<int64_t>((int64_t)pJson["credit_type_id"].asInt64());
        }
    }
    if(pJson.isMember("person_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["person_id"].isNull())
        {
            personId_=std::make_shared<int64_t>((int64_t)pJson["person_id"].asInt64());
        }
    }
    if(pJson.isMember("origin"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["origin"].isNull())
        {
            origin_=std::make_shared<int64_t>((int64_t)pJson["origin"].asInt64());
        }
    }
    if(pJson.isMember("external_id"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["external_id"].isNull())
        {
            externalId_=std::make_shared<std::string>(pJson["external_id"].asString());
        }
    }
}

void Credits::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            creditTypeId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            personId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            origin_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            externalId_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
}

void Credits::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("credit_type_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["credit_type_id"].isNull())
        {
            creditTypeId_=std::make_shared<int64_t>((int64_t)pJson["credit_type_id"].asInt64());
        }
    }
    if(pJson.isMember("person_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["person_id"].isNull())
        {
            personId_=std::make_shared<int64_t>((int64_t)pJson["person_id"].asInt64());
        }
    }
    if(pJson.isMember("origin"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["origin"].isNull())
        {
            origin_=std::make_shared<int64_t>((int64_t)pJson["origin"].asInt64());
        }
    }
    if(pJson.isMember("external_id"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["external_id"].isNull())
        {
            externalId_=std::make_shared<std::string>(pJson["external_id"].asString());
        }
    }
}

const int64_t &Credits::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Credits::getId() const noexcept
{
    return id_;
}
void Credits::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Credits::PrimaryKeyType & Credits::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &Credits::getValueOfCreditTypeId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(creditTypeId_)
        return *creditTypeId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Credits::getCreditTypeId() const noexcept
{
    return creditTypeId_;
}
void Credits::setCreditTypeId(const int64_t &pCreditTypeId) noexcept
{
    creditTypeId_ = std::make_shared<int64_t>(pCreditTypeId);
    dirtyFlag_[1] = true;
}

const int64_t &Credits::getValueOfPersonId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(personId_)
        return *personId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Credits::getPersonId() const noexcept
{
    return personId_;
}
void Credits::setPersonId(const int64_t &pPersonId) noexcept
{
    personId_ = std::make_shared<int64_t>(pPersonId);
    dirtyFlag_[2] = true;
}

const int64_t &Credits::getValueOfOrigin() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(origin_)
        return *origin_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Credits::getOrigin() const noexcept
{
    return origin_;
}
void Credits::setOrigin(const int64_t &pOrigin) noexcept
{
    origin_ = std::make_shared<int64_t>(pOrigin);
    dirtyFlag_[3] = true;
}

const std::string &Credits::getValueOfExternalId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(externalId_)
        return *externalId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Credits::getExternalId() const noexcept
{
    return externalId_;
}
void Credits::setExternalId(const std::string &pExternalId) noexcept
{
    externalId_ = std::make_shared<std::string>(pExternalId);
    dirtyFlag_[4] = true;
}
void Credits::setExternalId(std::string &&pExternalId) noexcept
{
    externalId_ = std::make_shared<std::string>(std::move(pExternalId));
    dirtyFlag_[4] = true;
}

void Credits::updateId(const uint64_t id)
{
    id_ = std::make_shared<int64_t>(static_cast<int64_t>(id));
}

const std::vector<std::string> &Credits::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "credit_type_id",
        "person_id",
        "origin",
        "external_id"
    };
    return inCols;
}

void Credits::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getCreditTypeId())
        {
            binder << getValueOfCreditTypeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPersonId())
        {
            binder << getValueOfPersonId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getOrigin())
        {
            binder << getValueOfOrigin();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getExternalId())
        {
            binder << getValueOfExternalId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Credits::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    return ret;
}

void Credits::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getCreditTypeId())
        {
            binder << getValueOfCreditTypeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPersonId())
        {
            binder << getValueOfPersonId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getOrigin())
        {
            binder << getValueOfOrigin();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getExternalId())
        {
            binder << getValueOfExternalId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Credits::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getCreditTypeId())
    {
        ret["credit_type_id"]=(Json::Int64)getValueOfCreditTypeId();
    }
    else
    {
        ret["credit_type_id"]=Json::Value();
    }
    if(getPersonId())
    {
        ret["person_id"]=(Json::Int64)getValueOfPersonId();
    }
    else
    {
        ret["person_id"]=Json::Value();
    }
    if(getOrigin())
    {
        ret["origin"]=(Json::Int64)getValueOfOrigin();
    }
    else
    {
        ret["origin"]=Json::Value();
    }
    if(getExternalId())
    {
        ret["external_id"]=getValueOfExternalId();
    }
    else
    {
        ret["external_id"]=Json::Value();
    }
    return ret;
}

std::string Credits::toString() const
{
    return toJson().toStyledString();
}

Json::Value Credits::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 5)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getCreditTypeId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfCreditTypeId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getPersonId())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfPersonId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getOrigin())
            {
                ret[pMasqueradingVector[3]]=(Json::Int64)getValueOfOrigin();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getExternalId())
            {
                ret[pMasqueradingVector[4]]=getValueOfExternalId();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getCreditTypeId())
    {
        ret["credit_type_id"]=(Json::Int64)getValueOfCreditTypeId();
    }
    else
    {
        ret["credit_type_id"]=Json::Value();
    }
    if(getPersonId())
    {
        ret["person_id"]=(Json::Int64)getValueOfPersonId();
    }
    else
    {
        ret["person_id"]=Json::Value();
    }
    if(getOrigin())
    {
        ret["origin"]=(Json::Int64)getValueOfOrigin();
    }
    else
    {
        ret["origin"]=Json::Value();
    }
    if(getExternalId())
    {
        ret["external_id"]=getValueOfExternalId();
    }
    else
    {
        ret["external_id"]=Json::Value();
    }
    return ret;
}

bool Credits::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("credit_type_id"))
    {
        if(!validJsonOfField(1, "credit_type_id", pJson["credit_type_id"], err, true))
            return false;
    }
    else
    {
        err="The credit_type_id column cannot be null";
        return false;
    }
    if(pJson.isMember("person_id"))
    {
        if(!validJsonOfField(2, "person_id", pJson["person_id"], err, true))
            return false;
    }
    else
    {
        err="The person_id column cannot be null";
        return false;
    }
    if(pJson.isMember("origin"))
    {
        if(!validJsonOfField(3, "origin", pJson["origin"], err, true))
            return false;
    }
    else
    {
        err="The origin column cannot be null";
        return false;
    }
    if(pJson.isMember("external_id"))
    {
        if(!validJsonOfField(4, "external_id", pJson["external_id"], err, true))
            return false;
    }
    else
    {
        err="The external_id column cannot be null";
        return false;
    }
    return true;
}
bool Credits::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Credits::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("credit_type_id"))
    {
        if(!validJsonOfField(1, "credit_type_id", pJson["credit_type_id"], err, false))
            return false;
    }
    if(pJson.isMember("person_id"))
    {
        if(!validJsonOfField(2, "person_id", pJson["person_id"], err, false))
            return false;
    }
    if(pJson.isMember("origin"))
    {
        if(!validJsonOfField(3, "origin", pJson["origin"], err, false))
            return false;
    }
    if(pJson.isMember("external_id"))
    {
        if(!validJsonOfField(4, "external_id", pJson["external_id"], err, false))
            return false;
    }
    return true;
}
bool Credits::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Credits::validJsonOfField(size_t index,
                               const std::string &fieldName,
                               const Json::Value &pJson,
                               std::string &err,
                               bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
