/**
 *
 *  Images.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Images.h"
#include "MediaItemImageAssignments.h"
#include "MediaItems.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string Images::Cols::_id = "id";
const std::string Images::Cols::_image_type_id = "image_type_id";
const std::string Images::Cols::_language_id = "language_id";
const std::string Images::Cols::_path = "path";
const std::string Images::Cols::_origin = "origin";
const std::string Images::Cols::_image_link = "image_link";
const std::string Images::primaryKeyName = "id";
const bool Images::hasPrimaryKey = true;
const std::string Images::tableName = "images";

const std::vector<typename Images::MetaData> Images::metaData_={
{"id","int64_t","integer",8,1,1,1},
{"image_type_id","int64_t","integer",8,0,0,1},
{"language_id","int64_t","integer",8,0,0,1},
{"path","std::string","text",0,0,0,1},
{"origin","int64_t","integer",8,0,0,1},
{"image_link","std::string","text",0,0,0,0}
};
const std::string &Images::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Images::Images(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["image_type_id"].isNull())
        {
            imageTypeId_=std::make_shared<int64_t>(r["image_type_id"].as<int64_t>());
        }
        if(!r["language_id"].isNull())
        {
            languageId_=std::make_shared<int64_t>(r["language_id"].as<int64_t>());
        }
        if(!r["path"].isNull())
        {
            path_=std::make_shared<std::string>(r["path"].as<std::string>());
        }
        if(!r["origin"].isNull())
        {
            origin_=std::make_shared<int64_t>(r["origin"].as<int64_t>());
        }
        if(!r["image_link"].isNull())
        {
            imageLink_=std::make_shared<std::string>(r["image_link"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 6 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            imageTypeId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            languageId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            path_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            origin_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            imageLink_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Images::Images(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            imageTypeId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            languageId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            path_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            origin_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            imageLink_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
}

Images::Images(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("image_type_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["image_type_id"].isNull())
        {
            imageTypeId_=std::make_shared<int64_t>((int64_t)pJson["image_type_id"].asInt64());
        }
    }
    if(pJson.isMember("language_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["language_id"].isNull())
        {
            languageId_=std::make_shared<int64_t>((int64_t)pJson["language_id"].asInt64());
        }
    }
    if(pJson.isMember("path"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["path"].isNull())
        {
            path_=std::make_shared<std::string>(pJson["path"].asString());
        }
    }
    if(pJson.isMember("origin"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["origin"].isNull())
        {
            origin_=std::make_shared<int64_t>((int64_t)pJson["origin"].asInt64());
        }
    }
    if(pJson.isMember("image_link"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["image_link"].isNull())
        {
            imageLink_=std::make_shared<std::string>(pJson["image_link"].asString());
        }
    }
}

void Images::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            imageTypeId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            languageId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            path_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            origin_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            imageLink_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
}

void Images::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("image_type_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["image_type_id"].isNull())
        {
            imageTypeId_=std::make_shared<int64_t>((int64_t)pJson["image_type_id"].asInt64());
        }
    }
    if(pJson.isMember("language_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["language_id"].isNull())
        {
            languageId_=std::make_shared<int64_t>((int64_t)pJson["language_id"].asInt64());
        }
    }
    if(pJson.isMember("path"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["path"].isNull())
        {
            path_=std::make_shared<std::string>(pJson["path"].asString());
        }
    }
    if(pJson.isMember("origin"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["origin"].isNull())
        {
            origin_=std::make_shared<int64_t>((int64_t)pJson["origin"].asInt64());
        }
    }
    if(pJson.isMember("image_link"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["image_link"].isNull())
        {
            imageLink_=std::make_shared<std::string>(pJson["image_link"].asString());
        }
    }
}

const int64_t &Images::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Images::getId() const noexcept
{
    return id_;
}
void Images::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Images::PrimaryKeyType & Images::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &Images::getValueOfImageTypeId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(imageTypeId_)
        return *imageTypeId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Images::getImageTypeId() const noexcept
{
    return imageTypeId_;
}
void Images::setImageTypeId(const int64_t &pImageTypeId) noexcept
{
    imageTypeId_ = std::make_shared<int64_t>(pImageTypeId);
    dirtyFlag_[1] = true;
}

const int64_t &Images::getValueOfLanguageId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(languageId_)
        return *languageId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Images::getLanguageId() const noexcept
{
    return languageId_;
}
void Images::setLanguageId(const int64_t &pLanguageId) noexcept
{
    languageId_ = std::make_shared<int64_t>(pLanguageId);
    dirtyFlag_[2] = true;
}

const std::string &Images::getValueOfPath() const noexcept
{
    static const std::string defaultValue = std::string();
    if(path_)
        return *path_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Images::getPath() const noexcept
{
    return path_;
}
void Images::setPath(const std::string &pPath) noexcept
{
    path_ = std::make_shared<std::string>(pPath);
    dirtyFlag_[3] = true;
}
void Images::setPath(std::string &&pPath) noexcept
{
    path_ = std::make_shared<std::string>(std::move(pPath));
    dirtyFlag_[3] = true;
}

const int64_t &Images::getValueOfOrigin() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(origin_)
        return *origin_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Images::getOrigin() const noexcept
{
    return origin_;
}
void Images::setOrigin(const int64_t &pOrigin) noexcept
{
    origin_ = std::make_shared<int64_t>(pOrigin);
    dirtyFlag_[4] = true;
}

const std::string &Images::getValueOfImageLink() const noexcept
{
    static const std::string defaultValue = std::string();
    if(imageLink_)
        return *imageLink_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Images::getImageLink() const noexcept
{
    return imageLink_;
}
void Images::setImageLink(const std::string &pImageLink) noexcept
{
    imageLink_ = std::make_shared<std::string>(pImageLink);
    dirtyFlag_[5] = true;
}
void Images::setImageLink(std::string &&pImageLink) noexcept
{
    imageLink_ = std::make_shared<std::string>(std::move(pImageLink));
    dirtyFlag_[5] = true;
}
void Images::setImageLinkToNull() noexcept
{
    imageLink_.reset();
    dirtyFlag_[5] = true;
}

void Images::updateId(const uint64_t id)
{
    id_ = std::make_shared<int64_t>(static_cast<int64_t>(id));
}

const std::vector<std::string> &Images::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "image_type_id",
        "language_id",
        "path",
        "origin",
        "image_link"
    };
    return inCols;
}

void Images::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getImageTypeId())
        {
            binder << getValueOfImageTypeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getLanguageId())
        {
            binder << getValueOfLanguageId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getPath())
        {
            binder << getValueOfPath();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getOrigin())
        {
            binder << getValueOfOrigin();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getImageLink())
        {
            binder << getValueOfImageLink();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Images::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void Images::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getImageTypeId())
        {
            binder << getValueOfImageTypeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getLanguageId())
        {
            binder << getValueOfLanguageId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getPath())
        {
            binder << getValueOfPath();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getOrigin())
        {
            binder << getValueOfOrigin();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getImageLink())
        {
            binder << getValueOfImageLink();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Images::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getImageTypeId())
    {
        ret["image_type_id"]=(Json::Int64)getValueOfImageTypeId();
    }
    else
    {
        ret["image_type_id"]=Json::Value();
    }
    if(getLanguageId())
    {
        ret["language_id"]=(Json::Int64)getValueOfLanguageId();
    }
    else
    {
        ret["language_id"]=Json::Value();
    }
    if(getPath())
    {
        ret["path"]=getValueOfPath();
    }
    else
    {
        ret["path"]=Json::Value();
    }
    if(getOrigin())
    {
        ret["origin"]=(Json::Int64)getValueOfOrigin();
    }
    else
    {
        ret["origin"]=Json::Value();
    }
    if(getImageLink())
    {
        ret["image_link"]=getValueOfImageLink();
    }
    else
    {
        ret["image_link"]=Json::Value();
    }
    return ret;
}

std::string Images::toString() const
{
    return toJson().toStyledString();
}

Json::Value Images::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 6)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getImageTypeId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfImageTypeId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getLanguageId())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfLanguageId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getPath())
            {
                ret[pMasqueradingVector[3]]=getValueOfPath();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getOrigin())
            {
                ret[pMasqueradingVector[4]]=(Json::Int64)getValueOfOrigin();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getImageLink())
            {
                ret[pMasqueradingVector[5]]=getValueOfImageLink();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getImageTypeId())
    {
        ret["image_type_id"]=(Json::Int64)getValueOfImageTypeId();
    }
    else
    {
        ret["image_type_id"]=Json::Value();
    }
    if(getLanguageId())
    {
        ret["language_id"]=(Json::Int64)getValueOfLanguageId();
    }
    else
    {
        ret["language_id"]=Json::Value();
    }
    if(getPath())
    {
        ret["path"]=getValueOfPath();
    }
    else
    {
        ret["path"]=Json::Value();
    }
    if(getOrigin())
    {
        ret["origin"]=(Json::Int64)getValueOfOrigin();
    }
    else
    {
        ret["origin"]=Json::Value();
    }
    if(getImageLink())
    {
        ret["image_link"]=getValueOfImageLink();
    }
    else
    {
        ret["image_link"]=Json::Value();
    }
    return ret;
}

bool Images::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("image_type_id"))
    {
        if(!validJsonOfField(1, "image_type_id", pJson["image_type_id"], err, true))
            return false;
    }
    else
    {
        err="The image_type_id column cannot be null";
        return false;
    }
    if(pJson.isMember("language_id"))
    {
        if(!validJsonOfField(2, "language_id", pJson["language_id"], err, true))
            return false;
    }
    else
    {
        err="The language_id column cannot be null";
        return false;
    }
    if(pJson.isMember("path"))
    {
        if(!validJsonOfField(3, "path", pJson["path"], err, true))
            return false;
    }
    else
    {
        err="The path column cannot be null";
        return false;
    }
    if(pJson.isMember("origin"))
    {
        if(!validJsonOfField(4, "origin", pJson["origin"], err, true))
            return false;
    }
    else
    {
        err="The origin column cannot be null";
        return false;
    }
    if(pJson.isMember("image_link"))
    {
        if(!validJsonOfField(5, "image_link", pJson["image_link"], err, true))
            return false;
    }
    return true;
}
bool Images::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Images::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("image_type_id"))
    {
        if(!validJsonOfField(1, "image_type_id", pJson["image_type_id"], err, false))
            return false;
    }
    if(pJson.isMember("language_id"))
    {
        if(!validJsonOfField(2, "language_id", pJson["language_id"], err, false))
            return false;
    }
    if(pJson.isMember("path"))
    {
        if(!validJsonOfField(3, "path", pJson["path"], err, false))
            return false;
    }
    if(pJson.isMember("origin"))
    {
        if(!validJsonOfField(4, "origin", pJson["origin"], err, false))
            return false;
    }
    if(pJson.isMember("image_link"))
    {
        if(!validJsonOfField(5, "image_link", pJson["image_link"], err, false))
            return false;
    }
    return true;
}
bool Images::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                              const std::vector<std::string> &pMasqueradingVector,
                                              std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Images::validJsonOfField(size_t index,
                              const std::string &fieldName,
                              const Json::Value &pJson,
                              std::string &err,
                              bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
std::vector<std::pair<MediaItems,MediaItemImageAssignments>> Images::getMediaItems(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from media_items,media_item_image_assignments where media_item_image_assignments.image_id = ? and media_item_image_assignments.media_item_id = media_items.id";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *id_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    std::vector<std::pair<MediaItems,MediaItemImageAssignments>> ret;
    ret.reserve(r.size());
    for (auto const &row : r)
    {
        ret.emplace_back(std::pair<MediaItems,MediaItemImageAssignments>(
            MediaItems(row),MediaItemImageAssignments(row,MediaItems::getColumnNumber())));
    }
    return ret;
}

void Images::getMediaItems(const DbClientPtr &clientPtr,
                           const std::function<void(std::vector<std::pair<MediaItems,MediaItemImageAssignments>>)> &rcb,
                           const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from media_items,media_item_image_assignments where media_item_image_assignments.image_id = ? and media_item_image_assignments.media_item_id = media_items.id";
    *clientPtr << sql
               << *id_
               >> [rcb = std::move(rcb)](const Result &r){
                   std::vector<std::pair<MediaItems,MediaItemImageAssignments>> ret;
                   ret.reserve(r.size());
                   for (auto const &row : r)
                   {
                       ret.emplace_back(std::pair<MediaItems,MediaItemImageAssignments>(
                           MediaItems(row),MediaItemImageAssignments(row,MediaItems::getColumnNumber())));
                   }
                   rcb(ret);
               }
               >> ecb;
}
