/**
 *
 *  MediaItemRatings.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "MediaItemRatings.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string MediaItemRatings::Cols::_id = "id";
const std::string MediaItemRatings::Cols::_media_item_id = "media_item_id";
const std::string MediaItemRatings::Cols::_metadata_provider_id = "metadata_provider_id";
const std::string MediaItemRatings::Cols::_rating = "rating";
const std::string MediaItemRatings::primaryKeyName = "id";
const bool MediaItemRatings::hasPrimaryKey = true;
const std::string MediaItemRatings::tableName = "media_item_ratings";

const std::vector<typename MediaItemRatings::MetaData> MediaItemRatings::metaData_={
{"id","int64_t","integer",8,1,1,1},
{"media_item_id","int64_t","integer",8,0,0,1},
{"metadata_provider_id","int64_t","integer",8,0,0,1},
{"rating","double","real",8,0,0,1}
};
const std::string &MediaItemRatings::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
MediaItemRatings::MediaItemRatings(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["media_item_id"].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>(r["media_item_id"].as<int64_t>());
        }
        if(!r["metadata_provider_id"].isNull())
        {
            metadataProviderId_=std::make_shared<int64_t>(r["metadata_provider_id"].as<int64_t>());
        }
        if(!r["rating"].isNull())
        {
            rating_=std::make_shared<double>(r["rating"].as<double>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            metadataProviderId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            rating_=std::make_shared<double>(r[index].as<double>());
        }
    }

}

MediaItemRatings::MediaItemRatings(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            metadataProviderId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            rating_=std::make_shared<double>(pJson[pMasqueradingVector[3]].asDouble());
        }
    }
}

MediaItemRatings::MediaItemRatings(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("media_item_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["media_item_id"].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>((int64_t)pJson["media_item_id"].asInt64());
        }
    }
    if(pJson.isMember("metadata_provider_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["metadata_provider_id"].isNull())
        {
            metadataProviderId_=std::make_shared<int64_t>((int64_t)pJson["metadata_provider_id"].asInt64());
        }
    }
    if(pJson.isMember("rating"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["rating"].isNull())
        {
            rating_=std::make_shared<double>(pJson["rating"].asDouble());
        }
    }
}

void MediaItemRatings::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            metadataProviderId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            rating_=std::make_shared<double>(pJson[pMasqueradingVector[3]].asDouble());
        }
    }
}

void MediaItemRatings::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("media_item_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["media_item_id"].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>((int64_t)pJson["media_item_id"].asInt64());
        }
    }
    if(pJson.isMember("metadata_provider_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["metadata_provider_id"].isNull())
        {
            metadataProviderId_=std::make_shared<int64_t>((int64_t)pJson["metadata_provider_id"].asInt64());
        }
    }
    if(pJson.isMember("rating"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["rating"].isNull())
        {
            rating_=std::make_shared<double>(pJson["rating"].asDouble());
        }
    }
}

const int64_t &MediaItemRatings::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MediaItemRatings::getId() const noexcept
{
    return id_;
}
void MediaItemRatings::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename MediaItemRatings::PrimaryKeyType & MediaItemRatings::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &MediaItemRatings::getValueOfMediaItemId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(mediaItemId_)
        return *mediaItemId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MediaItemRatings::getMediaItemId() const noexcept
{
    return mediaItemId_;
}
void MediaItemRatings::setMediaItemId(const int64_t &pMediaItemId) noexcept
{
    mediaItemId_ = std::make_shared<int64_t>(pMediaItemId);
    dirtyFlag_[1] = true;
}

const int64_t &MediaItemRatings::getValueOfMetadataProviderId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(metadataProviderId_)
        return *metadataProviderId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MediaItemRatings::getMetadataProviderId() const noexcept
{
    return metadataProviderId_;
}
void MediaItemRatings::setMetadataProviderId(const int64_t &pMetadataProviderId) noexcept
{
    metadataProviderId_ = std::make_shared<int64_t>(pMetadataProviderId);
    dirtyFlag_[2] = true;
}

const double &MediaItemRatings::getValueOfRating() const noexcept
{
    static const double defaultValue = double();
    if(rating_)
        return *rating_;
    return defaultValue;
}
const std::shared_ptr<double> &MediaItemRatings::getRating() const noexcept
{
    return rating_;
}
void MediaItemRatings::setRating(const double &pRating) noexcept
{
    rating_ = std::make_shared<double>(pRating);
    dirtyFlag_[3] = true;
}

void MediaItemRatings::updateId(const uint64_t id)
{
    id_ = std::make_shared<int64_t>(static_cast<int64_t>(id));
}

const std::vector<std::string> &MediaItemRatings::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "media_item_id",
        "metadata_provider_id",
        "rating"
    };
    return inCols;
}

void MediaItemRatings::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMediaItemId())
        {
            binder << getValueOfMediaItemId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getMetadataProviderId())
        {
            binder << getValueOfMetadataProviderId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getRating())
        {
            binder << getValueOfRating();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> MediaItemRatings::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void MediaItemRatings::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMediaItemId())
        {
            binder << getValueOfMediaItemId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getMetadataProviderId())
        {
            binder << getValueOfMetadataProviderId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getRating())
        {
            binder << getValueOfRating();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value MediaItemRatings::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMediaItemId())
    {
        ret["media_item_id"]=(Json::Int64)getValueOfMediaItemId();
    }
    else
    {
        ret["media_item_id"]=Json::Value();
    }
    if(getMetadataProviderId())
    {
        ret["metadata_provider_id"]=(Json::Int64)getValueOfMetadataProviderId();
    }
    else
    {
        ret["metadata_provider_id"]=Json::Value();
    }
    if(getRating())
    {
        ret["rating"]=getValueOfRating();
    }
    else
    {
        ret["rating"]=Json::Value();
    }
    return ret;
}

std::string MediaItemRatings::toString() const
{
    return toJson().toStyledString();
}

Json::Value MediaItemRatings::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getMediaItemId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfMediaItemId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getMetadataProviderId())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfMetadataProviderId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getRating())
            {
                ret[pMasqueradingVector[3]]=getValueOfRating();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMediaItemId())
    {
        ret["media_item_id"]=(Json::Int64)getValueOfMediaItemId();
    }
    else
    {
        ret["media_item_id"]=Json::Value();
    }
    if(getMetadataProviderId())
    {
        ret["metadata_provider_id"]=(Json::Int64)getValueOfMetadataProviderId();
    }
    else
    {
        ret["metadata_provider_id"]=Json::Value();
    }
    if(getRating())
    {
        ret["rating"]=getValueOfRating();
    }
    else
    {
        ret["rating"]=Json::Value();
    }
    return ret;
}

bool MediaItemRatings::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("media_item_id"))
    {
        if(!validJsonOfField(1, "media_item_id", pJson["media_item_id"], err, true))
            return false;
    }
    else
    {
        err="The media_item_id column cannot be null";
        return false;
    }
    if(pJson.isMember("metadata_provider_id"))
    {
        if(!validJsonOfField(2, "metadata_provider_id", pJson["metadata_provider_id"], err, true))
            return false;
    }
    else
    {
        err="The metadata_provider_id column cannot be null";
        return false;
    }
    if(pJson.isMember("rating"))
    {
        if(!validJsonOfField(3, "rating", pJson["rating"], err, true))
            return false;
    }
    else
    {
        err="The rating column cannot be null";
        return false;
    }
    return true;
}
bool MediaItemRatings::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                          const std::vector<std::string> &pMasqueradingVector,
                                                          std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MediaItemRatings::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("media_item_id"))
    {
        if(!validJsonOfField(1, "media_item_id", pJson["media_item_id"], err, false))
            return false;
    }
    if(pJson.isMember("metadata_provider_id"))
    {
        if(!validJsonOfField(2, "metadata_provider_id", pJson["metadata_provider_id"], err, false))
            return false;
    }
    if(pJson.isMember("rating"))
    {
        if(!validJsonOfField(3, "rating", pJson["rating"], err, false))
            return false;
    }
    return true;
}
bool MediaItemRatings::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                        const std::vector<std::string> &pMasqueradingVector,
                                                        std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MediaItemRatings::validJsonOfField(size_t index,
                                        const std::string &fieldName,
                                        const Json::Value &pJson,
                                        std::string &err,
                                        bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
