/**
 *
 *  MediaItems.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "MediaItems.h"
#include "ExternalMediaItemIds.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string MediaItems::Cols::_id = "id";
const std::string MediaItems::Cols::_parent_id = "parent_id";
const std::string MediaItems::Cols::_media_item_type_id = "media_item_type_id";
const std::string MediaItems::Cols::_season = "season";
const std::string MediaItems::Cols::_episode = "episode";
const std::string MediaItems::Cols::_path = "path";
const std::string MediaItems::Cols::_parsed_name = "parsed_name";
const std::string MediaItems::Cols::_last_updated = "last_updated";
const std::string MediaItems::Cols::_hls_stream_folder_path = "hls_stream_folder_path";
const std::string MediaItems::Cols::_hls_stream_last_accessed = "hls_stream_last_accessed";
const std::string MediaItems::Cols::_release_date = "release_date";
const std::string MediaItems::primaryKeyName = "id";
const bool MediaItems::hasPrimaryKey = true;
const std::string MediaItems::tableName = "media_items";

const std::vector<typename MediaItems::MetaData> MediaItems::metaData_={
{"id","int64_t","integer",8,1,1,1},
{"parent_id","int64_t","integer",8,0,0,0},
{"media_item_type_id","int64_t","integer",8,0,0,1},
{"season","int64_t","integer",8,0,0,0},
{"episode","int64_t","integer",8,0,0,0},
{"path","std::string","text",0,0,0,0},
{"parsed_name","std::string","text",0,0,0,0},
{"last_updated","std::string","text",0,0,0,1},
{"hls_stream_folder_path","std::string","text",0,0,0,0},
{"hls_stream_last_accessed","std::string","text",0,0,0,0},
{"release_date","std::string","text",0,0,0,0}
};
const std::string &MediaItems::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
MediaItems::MediaItems(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["parent_id"].isNull())
        {
            parentId_=std::make_shared<int64_t>(r["parent_id"].as<int64_t>());
        }
        if(!r["media_item_type_id"].isNull())
        {
            mediaItemTypeId_=std::make_shared<int64_t>(r["media_item_type_id"].as<int64_t>());
        }
        if(!r["season"].isNull())
        {
            season_=std::make_shared<int64_t>(r["season"].as<int64_t>());
        }
        if(!r["episode"].isNull())
        {
            episode_=std::make_shared<int64_t>(r["episode"].as<int64_t>());
        }
        if(!r["path"].isNull())
        {
            path_=std::make_shared<std::string>(r["path"].as<std::string>());
        }
        if(!r["parsed_name"].isNull())
        {
            parsedName_=std::make_shared<std::string>(r["parsed_name"].as<std::string>());
        }
        if(!r["last_updated"].isNull())
        {
            lastUpdated_=std::make_shared<std::string>(r["last_updated"].as<std::string>());
        }
        if(!r["hls_stream_folder_path"].isNull())
        {
            hlsStreamFolderPath_=std::make_shared<std::string>(r["hls_stream_folder_path"].as<std::string>());
        }
        if(!r["hls_stream_last_accessed"].isNull())
        {
            hlsStreamLastAccessed_=std::make_shared<std::string>(r["hls_stream_last_accessed"].as<std::string>());
        }
        if(!r["release_date"].isNull())
        {
            releaseDate_=std::make_shared<std::string>(r["release_date"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 11 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            parentId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            mediaItemTypeId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            season_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            episode_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            path_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            parsedName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            lastUpdated_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            hlsStreamFolderPath_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            hlsStreamLastAccessed_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            releaseDate_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

MediaItems::MediaItems(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 11)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            parentId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            mediaItemTypeId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            season_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            episode_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            path_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            parsedName_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            lastUpdated_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            hlsStreamFolderPath_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            hlsStreamLastAccessed_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            releaseDate_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
}

MediaItems::MediaItems(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("parent_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["parent_id"].isNull())
        {
            parentId_=std::make_shared<int64_t>((int64_t)pJson["parent_id"].asInt64());
        }
    }
    if(pJson.isMember("media_item_type_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["media_item_type_id"].isNull())
        {
            mediaItemTypeId_=std::make_shared<int64_t>((int64_t)pJson["media_item_type_id"].asInt64());
        }
    }
    if(pJson.isMember("season"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["season"].isNull())
        {
            season_=std::make_shared<int64_t>((int64_t)pJson["season"].asInt64());
        }
    }
    if(pJson.isMember("episode"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["episode"].isNull())
        {
            episode_=std::make_shared<int64_t>((int64_t)pJson["episode"].asInt64());
        }
    }
    if(pJson.isMember("path"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["path"].isNull())
        {
            path_=std::make_shared<std::string>(pJson["path"].asString());
        }
    }
    if(pJson.isMember("parsed_name"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["parsed_name"].isNull())
        {
            parsedName_=std::make_shared<std::string>(pJson["parsed_name"].asString());
        }
    }
    if(pJson.isMember("last_updated"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["last_updated"].isNull())
        {
            lastUpdated_=std::make_shared<std::string>(pJson["last_updated"].asString());
        }
    }
    if(pJson.isMember("hls_stream_folder_path"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["hls_stream_folder_path"].isNull())
        {
            hlsStreamFolderPath_=std::make_shared<std::string>(pJson["hls_stream_folder_path"].asString());
        }
    }
    if(pJson.isMember("hls_stream_last_accessed"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["hls_stream_last_accessed"].isNull())
        {
            hlsStreamLastAccessed_=std::make_shared<std::string>(pJson["hls_stream_last_accessed"].asString());
        }
    }
    if(pJson.isMember("release_date"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["release_date"].isNull())
        {
            releaseDate_=std::make_shared<std::string>(pJson["release_date"].asString());
        }
    }
}

void MediaItems::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 11)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            parentId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            mediaItemTypeId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            season_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            episode_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            path_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            parsedName_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            lastUpdated_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            hlsStreamFolderPath_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            hlsStreamLastAccessed_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            releaseDate_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
}

void MediaItems::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("parent_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["parent_id"].isNull())
        {
            parentId_=std::make_shared<int64_t>((int64_t)pJson["parent_id"].asInt64());
        }
    }
    if(pJson.isMember("media_item_type_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["media_item_type_id"].isNull())
        {
            mediaItemTypeId_=std::make_shared<int64_t>((int64_t)pJson["media_item_type_id"].asInt64());
        }
    }
    if(pJson.isMember("season"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["season"].isNull())
        {
            season_=std::make_shared<int64_t>((int64_t)pJson["season"].asInt64());
        }
    }
    if(pJson.isMember("episode"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["episode"].isNull())
        {
            episode_=std::make_shared<int64_t>((int64_t)pJson["episode"].asInt64());
        }
    }
    if(pJson.isMember("path"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["path"].isNull())
        {
            path_=std::make_shared<std::string>(pJson["path"].asString());
        }
    }
    if(pJson.isMember("parsed_name"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["parsed_name"].isNull())
        {
            parsedName_=std::make_shared<std::string>(pJson["parsed_name"].asString());
        }
    }
    if(pJson.isMember("last_updated"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["last_updated"].isNull())
        {
            lastUpdated_=std::make_shared<std::string>(pJson["last_updated"].asString());
        }
    }
    if(pJson.isMember("hls_stream_folder_path"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["hls_stream_folder_path"].isNull())
        {
            hlsStreamFolderPath_=std::make_shared<std::string>(pJson["hls_stream_folder_path"].asString());
        }
    }
    if(pJson.isMember("hls_stream_last_accessed"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["hls_stream_last_accessed"].isNull())
        {
            hlsStreamLastAccessed_=std::make_shared<std::string>(pJson["hls_stream_last_accessed"].asString());
        }
    }
    if(pJson.isMember("release_date"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["release_date"].isNull())
        {
            releaseDate_=std::make_shared<std::string>(pJson["release_date"].asString());
        }
    }
}

const int64_t &MediaItems::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MediaItems::getId() const noexcept
{
    return id_;
}
void MediaItems::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename MediaItems::PrimaryKeyType & MediaItems::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &MediaItems::getValueOfParentId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(parentId_)
        return *parentId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MediaItems::getParentId() const noexcept
{
    return parentId_;
}
void MediaItems::setParentId(const int64_t &pParentId) noexcept
{
    parentId_ = std::make_shared<int64_t>(pParentId);
    dirtyFlag_[1] = true;
}
void MediaItems::setParentIdToNull() noexcept
{
    parentId_.reset();
    dirtyFlag_[1] = true;
}

const int64_t &MediaItems::getValueOfMediaItemTypeId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(mediaItemTypeId_)
        return *mediaItemTypeId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MediaItems::getMediaItemTypeId() const noexcept
{
    return mediaItemTypeId_;
}
void MediaItems::setMediaItemTypeId(const int64_t &pMediaItemTypeId) noexcept
{
    mediaItemTypeId_ = std::make_shared<int64_t>(pMediaItemTypeId);
    dirtyFlag_[2] = true;
}

const int64_t &MediaItems::getValueOfSeason() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(season_)
        return *season_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MediaItems::getSeason() const noexcept
{
    return season_;
}
void MediaItems::setSeason(const int64_t &pSeason) noexcept
{
    season_ = std::make_shared<int64_t>(pSeason);
    dirtyFlag_[3] = true;
}
void MediaItems::setSeasonToNull() noexcept
{
    season_.reset();
    dirtyFlag_[3] = true;
}

const int64_t &MediaItems::getValueOfEpisode() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(episode_)
        return *episode_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MediaItems::getEpisode() const noexcept
{
    return episode_;
}
void MediaItems::setEpisode(const int64_t &pEpisode) noexcept
{
    episode_ = std::make_shared<int64_t>(pEpisode);
    dirtyFlag_[4] = true;
}
void MediaItems::setEpisodeToNull() noexcept
{
    episode_.reset();
    dirtyFlag_[4] = true;
}

const std::string &MediaItems::getValueOfPath() const noexcept
{
    static const std::string defaultValue = std::string();
    if(path_)
        return *path_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MediaItems::getPath() const noexcept
{
    return path_;
}
void MediaItems::setPath(const std::string &pPath) noexcept
{
    path_ = std::make_shared<std::string>(pPath);
    dirtyFlag_[5] = true;
}
void MediaItems::setPath(std::string &&pPath) noexcept
{
    path_ = std::make_shared<std::string>(std::move(pPath));
    dirtyFlag_[5] = true;
}
void MediaItems::setPathToNull() noexcept
{
    path_.reset();
    dirtyFlag_[5] = true;
}

const std::string &MediaItems::getValueOfParsedName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(parsedName_)
        return *parsedName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MediaItems::getParsedName() const noexcept
{
    return parsedName_;
}
void MediaItems::setParsedName(const std::string &pParsedName) noexcept
{
    parsedName_ = std::make_shared<std::string>(pParsedName);
    dirtyFlag_[6] = true;
}
void MediaItems::setParsedName(std::string &&pParsedName) noexcept
{
    parsedName_ = std::make_shared<std::string>(std::move(pParsedName));
    dirtyFlag_[6] = true;
}
void MediaItems::setParsedNameToNull() noexcept
{
    parsedName_.reset();
    dirtyFlag_[6] = true;
}

const std::string &MediaItems::getValueOfLastUpdated() const noexcept
{
    static const std::string defaultValue = std::string();
    if(lastUpdated_)
        return *lastUpdated_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MediaItems::getLastUpdated() const noexcept
{
    return lastUpdated_;
}
void MediaItems::setLastUpdated(const std::string &pLastUpdated) noexcept
{
    lastUpdated_ = std::make_shared<std::string>(pLastUpdated);
    dirtyFlag_[7] = true;
}
void MediaItems::setLastUpdated(std::string &&pLastUpdated) noexcept
{
    lastUpdated_ = std::make_shared<std::string>(std::move(pLastUpdated));
    dirtyFlag_[7] = true;
}

const std::string &MediaItems::getValueOfHlsStreamFolderPath() const noexcept
{
    static const std::string defaultValue = std::string();
    if(hlsStreamFolderPath_)
        return *hlsStreamFolderPath_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MediaItems::getHlsStreamFolderPath() const noexcept
{
    return hlsStreamFolderPath_;
}
void MediaItems::setHlsStreamFolderPath(const std::string &pHlsStreamFolderPath) noexcept
{
    hlsStreamFolderPath_ = std::make_shared<std::string>(pHlsStreamFolderPath);
    dirtyFlag_[8] = true;
}
void MediaItems::setHlsStreamFolderPath(std::string &&pHlsStreamFolderPath) noexcept
{
    hlsStreamFolderPath_ = std::make_shared<std::string>(std::move(pHlsStreamFolderPath));
    dirtyFlag_[8] = true;
}
void MediaItems::setHlsStreamFolderPathToNull() noexcept
{
    hlsStreamFolderPath_.reset();
    dirtyFlag_[8] = true;
}

const std::string &MediaItems::getValueOfHlsStreamLastAccessed() const noexcept
{
    static const std::string defaultValue = std::string();
    if(hlsStreamLastAccessed_)
        return *hlsStreamLastAccessed_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MediaItems::getHlsStreamLastAccessed() const noexcept
{
    return hlsStreamLastAccessed_;
}
void MediaItems::setHlsStreamLastAccessed(const std::string &pHlsStreamLastAccessed) noexcept
{
    hlsStreamLastAccessed_ = std::make_shared<std::string>(pHlsStreamLastAccessed);
    dirtyFlag_[9] = true;
}
void MediaItems::setHlsStreamLastAccessed(std::string &&pHlsStreamLastAccessed) noexcept
{
    hlsStreamLastAccessed_ = std::make_shared<std::string>(std::move(pHlsStreamLastAccessed));
    dirtyFlag_[9] = true;
}
void MediaItems::setHlsStreamLastAccessedToNull() noexcept
{
    hlsStreamLastAccessed_.reset();
    dirtyFlag_[9] = true;
}

const std::string &MediaItems::getValueOfReleaseDate() const noexcept
{
    static const std::string defaultValue = std::string();
    if(releaseDate_)
        return *releaseDate_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MediaItems::getReleaseDate() const noexcept
{
    return releaseDate_;
}
void MediaItems::setReleaseDate(const std::string &pReleaseDate) noexcept
{
    releaseDate_ = std::make_shared<std::string>(pReleaseDate);
    dirtyFlag_[10] = true;
}
void MediaItems::setReleaseDate(std::string &&pReleaseDate) noexcept
{
    releaseDate_ = std::make_shared<std::string>(std::move(pReleaseDate));
    dirtyFlag_[10] = true;
}
void MediaItems::setReleaseDateToNull() noexcept
{
    releaseDate_.reset();
    dirtyFlag_[10] = true;
}

void MediaItems::updateId(const uint64_t id)
{
    id_ = std::make_shared<int64_t>(static_cast<int64_t>(id));
}

const std::vector<std::string> &MediaItems::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "parent_id",
        "media_item_type_id",
        "season",
        "episode",
        "path",
        "parsed_name",
        "last_updated",
        "hls_stream_folder_path",
        "hls_stream_last_accessed",
        "release_date"
    };
    return inCols;
}

void MediaItems::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getParentId())
        {
            binder << getValueOfParentId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getMediaItemTypeId())
        {
            binder << getValueOfMediaItemTypeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSeason())
        {
            binder << getValueOfSeason();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getEpisode())
        {
            binder << getValueOfEpisode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getPath())
        {
            binder << getValueOfPath();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getParsedName())
        {
            binder << getValueOfParsedName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getLastUpdated())
        {
            binder << getValueOfLastUpdated();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getHlsStreamFolderPath())
        {
            binder << getValueOfHlsStreamFolderPath();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getHlsStreamLastAccessed())
        {
            binder << getValueOfHlsStreamLastAccessed();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getReleaseDate())
        {
            binder << getValueOfReleaseDate();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> MediaItems::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    return ret;
}

void MediaItems::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getParentId())
        {
            binder << getValueOfParentId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getMediaItemTypeId())
        {
            binder << getValueOfMediaItemTypeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSeason())
        {
            binder << getValueOfSeason();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getEpisode())
        {
            binder << getValueOfEpisode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getPath())
        {
            binder << getValueOfPath();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getParsedName())
        {
            binder << getValueOfParsedName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getLastUpdated())
        {
            binder << getValueOfLastUpdated();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getHlsStreamFolderPath())
        {
            binder << getValueOfHlsStreamFolderPath();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getHlsStreamLastAccessed())
        {
            binder << getValueOfHlsStreamLastAccessed();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getReleaseDate())
        {
            binder << getValueOfReleaseDate();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value MediaItems::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getParentId())
    {
        ret["parent_id"]=(Json::Int64)getValueOfParentId();
    }
    else
    {
        ret["parent_id"]=Json::Value();
    }
    if(getMediaItemTypeId())
    {
        ret["media_item_type_id"]=(Json::Int64)getValueOfMediaItemTypeId();
    }
    else
    {
        ret["media_item_type_id"]=Json::Value();
    }
    if(getSeason())
    {
        ret["season"]=(Json::Int64)getValueOfSeason();
    }
    else
    {
        ret["season"]=Json::Value();
    }
    if(getEpisode())
    {
        ret["episode"]=(Json::Int64)getValueOfEpisode();
    }
    else
    {
        ret["episode"]=Json::Value();
    }
    if(getPath())
    {
        ret["path"]=getValueOfPath();
    }
    else
    {
        ret["path"]=Json::Value();
    }
    if(getParsedName())
    {
        ret["parsed_name"]=getValueOfParsedName();
    }
    else
    {
        ret["parsed_name"]=Json::Value();
    }
    if(getLastUpdated())
    {
        ret["last_updated"]=getValueOfLastUpdated();
    }
    else
    {
        ret["last_updated"]=Json::Value();
    }
    if(getHlsStreamFolderPath())
    {
        ret["hls_stream_folder_path"]=getValueOfHlsStreamFolderPath();
    }
    else
    {
        ret["hls_stream_folder_path"]=Json::Value();
    }
    if(getHlsStreamLastAccessed())
    {
        ret["hls_stream_last_accessed"]=getValueOfHlsStreamLastAccessed();
    }
    else
    {
        ret["hls_stream_last_accessed"]=Json::Value();
    }
    if(getReleaseDate())
    {
        ret["release_date"]=getValueOfReleaseDate();
    }
    else
    {
        ret["release_date"]=Json::Value();
    }
    return ret;
}

std::string MediaItems::toString() const
{
    return toJson().toStyledString();
}

Json::Value MediaItems::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 11)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getParentId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfParentId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getMediaItemTypeId())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfMediaItemTypeId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getSeason())
            {
                ret[pMasqueradingVector[3]]=(Json::Int64)getValueOfSeason();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getEpisode())
            {
                ret[pMasqueradingVector[4]]=(Json::Int64)getValueOfEpisode();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getPath())
            {
                ret[pMasqueradingVector[5]]=getValueOfPath();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getParsedName())
            {
                ret[pMasqueradingVector[6]]=getValueOfParsedName();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getLastUpdated())
            {
                ret[pMasqueradingVector[7]]=getValueOfLastUpdated();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getHlsStreamFolderPath())
            {
                ret[pMasqueradingVector[8]]=getValueOfHlsStreamFolderPath();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getHlsStreamLastAccessed())
            {
                ret[pMasqueradingVector[9]]=getValueOfHlsStreamLastAccessed();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getReleaseDate())
            {
                ret[pMasqueradingVector[10]]=getValueOfReleaseDate();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getParentId())
    {
        ret["parent_id"]=(Json::Int64)getValueOfParentId();
    }
    else
    {
        ret["parent_id"]=Json::Value();
    }
    if(getMediaItemTypeId())
    {
        ret["media_item_type_id"]=(Json::Int64)getValueOfMediaItemTypeId();
    }
    else
    {
        ret["media_item_type_id"]=Json::Value();
    }
    if(getSeason())
    {
        ret["season"]=(Json::Int64)getValueOfSeason();
    }
    else
    {
        ret["season"]=Json::Value();
    }
    if(getEpisode())
    {
        ret["episode"]=(Json::Int64)getValueOfEpisode();
    }
    else
    {
        ret["episode"]=Json::Value();
    }
    if(getPath())
    {
        ret["path"]=getValueOfPath();
    }
    else
    {
        ret["path"]=Json::Value();
    }
    if(getParsedName())
    {
        ret["parsed_name"]=getValueOfParsedName();
    }
    else
    {
        ret["parsed_name"]=Json::Value();
    }
    if(getLastUpdated())
    {
        ret["last_updated"]=getValueOfLastUpdated();
    }
    else
    {
        ret["last_updated"]=Json::Value();
    }
    if(getHlsStreamFolderPath())
    {
        ret["hls_stream_folder_path"]=getValueOfHlsStreamFolderPath();
    }
    else
    {
        ret["hls_stream_folder_path"]=Json::Value();
    }
    if(getHlsStreamLastAccessed())
    {
        ret["hls_stream_last_accessed"]=getValueOfHlsStreamLastAccessed();
    }
    else
    {
        ret["hls_stream_last_accessed"]=Json::Value();
    }
    if(getReleaseDate())
    {
        ret["release_date"]=getValueOfReleaseDate();
    }
    else
    {
        ret["release_date"]=Json::Value();
    }
    return ret;
}

bool MediaItems::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("parent_id"))
    {
        if(!validJsonOfField(1, "parent_id", pJson["parent_id"], err, true))
            return false;
    }
    if(pJson.isMember("media_item_type_id"))
    {
        if(!validJsonOfField(2, "media_item_type_id", pJson["media_item_type_id"], err, true))
            return false;
    }
    else
    {
        err="The media_item_type_id column cannot be null";
        return false;
    }
    if(pJson.isMember("season"))
    {
        if(!validJsonOfField(3, "season", pJson["season"], err, true))
            return false;
    }
    if(pJson.isMember("episode"))
    {
        if(!validJsonOfField(4, "episode", pJson["episode"], err, true))
            return false;
    }
    if(pJson.isMember("path"))
    {
        if(!validJsonOfField(5, "path", pJson["path"], err, true))
            return false;
    }
    if(pJson.isMember("parsed_name"))
    {
        if(!validJsonOfField(6, "parsed_name", pJson["parsed_name"], err, true))
            return false;
    }
    if(pJson.isMember("last_updated"))
    {
        if(!validJsonOfField(7, "last_updated", pJson["last_updated"], err, true))
            return false;
    }
    else
    {
        err="The last_updated column cannot be null";
        return false;
    }
    if(pJson.isMember("hls_stream_folder_path"))
    {
        if(!validJsonOfField(8, "hls_stream_folder_path", pJson["hls_stream_folder_path"], err, true))
            return false;
    }
    if(pJson.isMember("hls_stream_last_accessed"))
    {
        if(!validJsonOfField(9, "hls_stream_last_accessed", pJson["hls_stream_last_accessed"], err, true))
            return false;
    }
    if(pJson.isMember("release_date"))
    {
        if(!validJsonOfField(10, "release_date", pJson["release_date"], err, true))
            return false;
    }
    return true;
}
bool MediaItems::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 11)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[7] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MediaItems::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("parent_id"))
    {
        if(!validJsonOfField(1, "parent_id", pJson["parent_id"], err, false))
            return false;
    }
    if(pJson.isMember("media_item_type_id"))
    {
        if(!validJsonOfField(2, "media_item_type_id", pJson["media_item_type_id"], err, false))
            return false;
    }
    if(pJson.isMember("season"))
    {
        if(!validJsonOfField(3, "season", pJson["season"], err, false))
            return false;
    }
    if(pJson.isMember("episode"))
    {
        if(!validJsonOfField(4, "episode", pJson["episode"], err, false))
            return false;
    }
    if(pJson.isMember("path"))
    {
        if(!validJsonOfField(5, "path", pJson["path"], err, false))
            return false;
    }
    if(pJson.isMember("parsed_name"))
    {
        if(!validJsonOfField(6, "parsed_name", pJson["parsed_name"], err, false))
            return false;
    }
    if(pJson.isMember("last_updated"))
    {
        if(!validJsonOfField(7, "last_updated", pJson["last_updated"], err, false))
            return false;
    }
    if(pJson.isMember("hls_stream_folder_path"))
    {
        if(!validJsonOfField(8, "hls_stream_folder_path", pJson["hls_stream_folder_path"], err, false))
            return false;
    }
    if(pJson.isMember("hls_stream_last_accessed"))
    {
        if(!validJsonOfField(9, "hls_stream_last_accessed", pJson["hls_stream_last_accessed"], err, false))
            return false;
    }
    if(pJson.isMember("release_date"))
    {
        if(!validJsonOfField(10, "release_date", pJson["release_date"], err, false))
            return false;
    }
    return true;
}
bool MediaItems::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 11)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MediaItems::validJsonOfField(size_t index,
                                  const std::string &fieldName,
                                  const Json::Value &pJson,
                                  std::string &err,
                                  bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
std::vector<ExternalMediaItemIds> MediaItems::getExternalMediaItemIds(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from external_media_item_ids where media_item_id = ?";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *id_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    std::vector<ExternalMediaItemIds> ret;
    ret.reserve(r.size());
    for (auto const &row : r)
    {
        ret.emplace_back(ExternalMediaItemIds(row));
    }
    return ret;
}

void MediaItems::getExternalMediaItemIds(const DbClientPtr &clientPtr,
                                         const std::function<void(std::vector<ExternalMediaItemIds>)> &rcb,
                                         const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from external_media_item_ids where media_item_id = ?";
    *clientPtr << sql
               << *id_
               >> [rcb = std::move(rcb)](const Result &r){
                   std::vector<ExternalMediaItemIds> ret;
                   ret.reserve(r.size());
                   for (auto const &row : r)
                   {
                       ret.emplace_back(ExternalMediaItemIds(row));
                   }
                   rcb(ret);
               }
               >> ecb;
}
