/**
 *
 *  MediaItems.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace sqlite3
{
class ExternalMediaItemIds;

class MediaItems
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _parent_id;
        static const std::string _media_item_type_id;
        static const std::string _season;
        static const std::string _episode;
        static const std::string _path;
        static const std::string _parsed_name;
        static const std::string _last_updated;
        static const std::string _hls_stream_folder_path;
        static const std::string _hls_stream_last_accessed;
        static const std::string _release_date;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit MediaItems(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit MediaItems(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    MediaItems(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    MediaItems() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int64_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int64_t &pId) noexcept;

    /**  For column parent_id  */
    ///Get the value of the column parent_id, returns the default value if the column is null
    const int64_t &getValueOfParentId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getParentId() const noexcept;
    ///Set the value of the column parent_id
    void setParentId(const int64_t &pParentId) noexcept;
    void setParentIdToNull() noexcept;

    /**  For column media_item_type_id  */
    ///Get the value of the column media_item_type_id, returns the default value if the column is null
    const int64_t &getValueOfMediaItemTypeId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getMediaItemTypeId() const noexcept;
    ///Set the value of the column media_item_type_id
    void setMediaItemTypeId(const int64_t &pMediaItemTypeId) noexcept;

    /**  For column season  */
    ///Get the value of the column season, returns the default value if the column is null
    const int64_t &getValueOfSeason() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getSeason() const noexcept;
    ///Set the value of the column season
    void setSeason(const int64_t &pSeason) noexcept;
    void setSeasonToNull() noexcept;

    /**  For column episode  */
    ///Get the value of the column episode, returns the default value if the column is null
    const int64_t &getValueOfEpisode() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getEpisode() const noexcept;
    ///Set the value of the column episode
    void setEpisode(const int64_t &pEpisode) noexcept;
    void setEpisodeToNull() noexcept;

    /**  For column path  */
    ///Get the value of the column path, returns the default value if the column is null
    const std::string &getValueOfPath() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPath() const noexcept;
    ///Set the value of the column path
    void setPath(const std::string &pPath) noexcept;
    void setPath(std::string &&pPath) noexcept;
    void setPathToNull() noexcept;

    /**  For column parsed_name  */
    ///Get the value of the column parsed_name, returns the default value if the column is null
    const std::string &getValueOfParsedName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getParsedName() const noexcept;
    ///Set the value of the column parsed_name
    void setParsedName(const std::string &pParsedName) noexcept;
    void setParsedName(std::string &&pParsedName) noexcept;
    void setParsedNameToNull() noexcept;

    /**  For column last_updated  */
    ///Get the value of the column last_updated, returns the default value if the column is null
    const std::string &getValueOfLastUpdated() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getLastUpdated() const noexcept;
    ///Set the value of the column last_updated
    void setLastUpdated(const std::string &pLastUpdated) noexcept;
    void setLastUpdated(std::string &&pLastUpdated) noexcept;

    /**  For column hls_stream_folder_path  */
    ///Get the value of the column hls_stream_folder_path, returns the default value if the column is null
    const std::string &getValueOfHlsStreamFolderPath() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getHlsStreamFolderPath() const noexcept;
    ///Set the value of the column hls_stream_folder_path
    void setHlsStreamFolderPath(const std::string &pHlsStreamFolderPath) noexcept;
    void setHlsStreamFolderPath(std::string &&pHlsStreamFolderPath) noexcept;
    void setHlsStreamFolderPathToNull() noexcept;

    /**  For column hls_stream_last_accessed  */
    ///Get the value of the column hls_stream_last_accessed, returns the default value if the column is null
    const std::string &getValueOfHlsStreamLastAccessed() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getHlsStreamLastAccessed() const noexcept;
    ///Set the value of the column hls_stream_last_accessed
    void setHlsStreamLastAccessed(const std::string &pHlsStreamLastAccessed) noexcept;
    void setHlsStreamLastAccessed(std::string &&pHlsStreamLastAccessed) noexcept;
    void setHlsStreamLastAccessedToNull() noexcept;

    /**  For column release_date  */
    ///Get the value of the column release_date, returns the default value if the column is null
    const std::string &getValueOfReleaseDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getReleaseDate() const noexcept;
    ///Set the value of the column release_date
    void setReleaseDate(const std::string &pReleaseDate) noexcept;
    void setReleaseDate(std::string &&pReleaseDate) noexcept;
    void setReleaseDateToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 11;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    std::vector<ExternalMediaItemIds> getExternalMediaItemIds(const drogon::orm::DbClientPtr &clientPtr) const;
    void getExternalMediaItemIds(const drogon::orm::DbClientPtr &clientPtr,
                                 const std::function<void(std::vector<ExternalMediaItemIds>)> &rcb,
                                 const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<MediaItems>;
    friend drogon::orm::BaseBuilder<MediaItems, true, true>;
    friend drogon::orm::BaseBuilder<MediaItems, true, false>;
    friend drogon::orm::BaseBuilder<MediaItems, false, true>;
    friend drogon::orm::BaseBuilder<MediaItems, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<MediaItems>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int64_t> id_;
    std::shared_ptr<int64_t> parentId_;
    std::shared_ptr<int64_t> mediaItemTypeId_;
    std::shared_ptr<int64_t> season_;
    std::shared_ptr<int64_t> episode_;
    std::shared_ptr<std::string> path_;
    std::shared_ptr<std::string> parsedName_;
    std::shared_ptr<std::string> lastUpdated_;
    std::shared_ptr<std::string> hlsStreamFolderPath_;
    std::shared_ptr<std::string> hlsStreamLastAccessed_;
    std::shared_ptr<std::string> releaseDate_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[11]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = ?";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = ?";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[1])
        {
            sql += "parent_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "media_item_type_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "season,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "episode,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "path,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "parsed_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "last_updated,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "hls_stream_folder_path,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "hls_stream_last_accessed,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "release_date,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        if(dirtyFlag_[1])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[7])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[8])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[9])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[10])
        {
            sql.append("?,");

        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace sqlite3
} // namespace drogon_model
