/**
 *
 *  MediaItemLocalizations.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "MediaItemLocalizations.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string MediaItemLocalizations::Cols::_id = "id";
const std::string MediaItemLocalizations::Cols::_media_item_id = "media_item_id";
const std::string MediaItemLocalizations::Cols::_language_id = "language_id";
const std::string MediaItemLocalizations::Cols::_name = "name";
const std::string MediaItemLocalizations::Cols::_description = "description";
const std::string MediaItemLocalizations::Cols::_tagline = "tagline";
const std::string MediaItemLocalizations::Cols::_original = "original";
const std::string MediaItemLocalizations::primaryKeyName = "id";
const bool MediaItemLocalizations::hasPrimaryKey = true;
const std::string MediaItemLocalizations::tableName = "media_item_localizations";

const std::vector<typename MediaItemLocalizations::MetaData> MediaItemLocalizations::metaData_={
{"id","int64_t","integer",8,1,1,1},
{"media_item_id","int64_t","integer",8,0,0,1},
{"language_id","int64_t","integer",8,0,0,1},
{"name","std::string","text",0,0,0,1},
{"description","std::string","text",0,0,0,1},
{"tagline","std::string","text",0,0,0,1},
{"original","int64_t","integer",8,0,0,1}
};
const std::string &MediaItemLocalizations::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
MediaItemLocalizations::MediaItemLocalizations(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["media_item_id"].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>(r["media_item_id"].as<int64_t>());
        }
        if(!r["language_id"].isNull())
        {
            languageId_=std::make_shared<int64_t>(r["language_id"].as<int64_t>());
        }
        if(!r["name"].isNull())
        {
            name_=std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if(!r["description"].isNull())
        {
            description_=std::make_shared<std::string>(r["description"].as<std::string>());
        }
        if(!r["tagline"].isNull())
        {
            tagline_=std::make_shared<std::string>(r["tagline"].as<std::string>());
        }
        if(!r["original"].isNull())
        {
            original_=std::make_shared<int64_t>(r["original"].as<int64_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 7 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            languageId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            name_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            description_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            tagline_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            original_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
    }

}

MediaItemLocalizations::MediaItemLocalizations(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            languageId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            description_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            tagline_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            original_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
}

MediaItemLocalizations::MediaItemLocalizations(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("media_item_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["media_item_id"].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>((int64_t)pJson["media_item_id"].asInt64());
        }
    }
    if(pJson.isMember("language_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["language_id"].isNull())
        {
            languageId_=std::make_shared<int64_t>((int64_t)pJson["language_id"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("description"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["description"].isNull())
        {
            description_=std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if(pJson.isMember("tagline"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["tagline"].isNull())
        {
            tagline_=std::make_shared<std::string>(pJson["tagline"].asString());
        }
    }
    if(pJson.isMember("original"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["original"].isNull())
        {
            original_=std::make_shared<int64_t>((int64_t)pJson["original"].asInt64());
        }
    }
}

void MediaItemLocalizations::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            languageId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            description_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            tagline_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            original_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
}

void MediaItemLocalizations::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("media_item_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["media_item_id"].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>((int64_t)pJson["media_item_id"].asInt64());
        }
    }
    if(pJson.isMember("language_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["language_id"].isNull())
        {
            languageId_=std::make_shared<int64_t>((int64_t)pJson["language_id"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("description"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["description"].isNull())
        {
            description_=std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if(pJson.isMember("tagline"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["tagline"].isNull())
        {
            tagline_=std::make_shared<std::string>(pJson["tagline"].asString());
        }
    }
    if(pJson.isMember("original"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["original"].isNull())
        {
            original_=std::make_shared<int64_t>((int64_t)pJson["original"].asInt64());
        }
    }
}

const int64_t &MediaItemLocalizations::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MediaItemLocalizations::getId() const noexcept
{
    return id_;
}
void MediaItemLocalizations::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename MediaItemLocalizations::PrimaryKeyType & MediaItemLocalizations::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &MediaItemLocalizations::getValueOfMediaItemId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(mediaItemId_)
        return *mediaItemId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MediaItemLocalizations::getMediaItemId() const noexcept
{
    return mediaItemId_;
}
void MediaItemLocalizations::setMediaItemId(const int64_t &pMediaItemId) noexcept
{
    mediaItemId_ = std::make_shared<int64_t>(pMediaItemId);
    dirtyFlag_[1] = true;
}

const int64_t &MediaItemLocalizations::getValueOfLanguageId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(languageId_)
        return *languageId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MediaItemLocalizations::getLanguageId() const noexcept
{
    return languageId_;
}
void MediaItemLocalizations::setLanguageId(const int64_t &pLanguageId) noexcept
{
    languageId_ = std::make_shared<int64_t>(pLanguageId);
    dirtyFlag_[2] = true;
}

const std::string &MediaItemLocalizations::getValueOfName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MediaItemLocalizations::getName() const noexcept
{
    return name_;
}
void MediaItemLocalizations::setName(const std::string &pName) noexcept
{
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[3] = true;
}
void MediaItemLocalizations::setName(std::string &&pName) noexcept
{
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[3] = true;
}

const std::string &MediaItemLocalizations::getValueOfDescription() const noexcept
{
    static const std::string defaultValue = std::string();
    if(description_)
        return *description_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MediaItemLocalizations::getDescription() const noexcept
{
    return description_;
}
void MediaItemLocalizations::setDescription(const std::string &pDescription) noexcept
{
    description_ = std::make_shared<std::string>(pDescription);
    dirtyFlag_[4] = true;
}
void MediaItemLocalizations::setDescription(std::string &&pDescription) noexcept
{
    description_ = std::make_shared<std::string>(std::move(pDescription));
    dirtyFlag_[4] = true;
}

const std::string &MediaItemLocalizations::getValueOfTagline() const noexcept
{
    static const std::string defaultValue = std::string();
    if(tagline_)
        return *tagline_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MediaItemLocalizations::getTagline() const noexcept
{
    return tagline_;
}
void MediaItemLocalizations::setTagline(const std::string &pTagline) noexcept
{
    tagline_ = std::make_shared<std::string>(pTagline);
    dirtyFlag_[5] = true;
}
void MediaItemLocalizations::setTagline(std::string &&pTagline) noexcept
{
    tagline_ = std::make_shared<std::string>(std::move(pTagline));
    dirtyFlag_[5] = true;
}

const int64_t &MediaItemLocalizations::getValueOfOriginal() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(original_)
        return *original_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MediaItemLocalizations::getOriginal() const noexcept
{
    return original_;
}
void MediaItemLocalizations::setOriginal(const int64_t &pOriginal) noexcept
{
    original_ = std::make_shared<int64_t>(pOriginal);
    dirtyFlag_[6] = true;
}

void MediaItemLocalizations::updateId(const uint64_t id)
{
    id_ = std::make_shared<int64_t>(static_cast<int64_t>(id));
}

const std::vector<std::string> &MediaItemLocalizations::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "media_item_id",
        "language_id",
        "name",
        "description",
        "tagline",
        "original"
    };
    return inCols;
}

void MediaItemLocalizations::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMediaItemId())
        {
            binder << getValueOfMediaItemId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getLanguageId())
        {
            binder << getValueOfLanguageId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getTagline())
        {
            binder << getValueOfTagline();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getOriginal())
        {
            binder << getValueOfOriginal();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> MediaItemLocalizations::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    return ret;
}

void MediaItemLocalizations::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMediaItemId())
        {
            binder << getValueOfMediaItemId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getLanguageId())
        {
            binder << getValueOfLanguageId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getTagline())
        {
            binder << getValueOfTagline();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getOriginal())
        {
            binder << getValueOfOriginal();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value MediaItemLocalizations::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMediaItemId())
    {
        ret["media_item_id"]=(Json::Int64)getValueOfMediaItemId();
    }
    else
    {
        ret["media_item_id"]=Json::Value();
    }
    if(getLanguageId())
    {
        ret["language_id"]=(Json::Int64)getValueOfLanguageId();
    }
    else
    {
        ret["language_id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getDescription())
    {
        ret["description"]=getValueOfDescription();
    }
    else
    {
        ret["description"]=Json::Value();
    }
    if(getTagline())
    {
        ret["tagline"]=getValueOfTagline();
    }
    else
    {
        ret["tagline"]=Json::Value();
    }
    if(getOriginal())
    {
        ret["original"]=(Json::Int64)getValueOfOriginal();
    }
    else
    {
        ret["original"]=Json::Value();
    }
    return ret;
}

std::string MediaItemLocalizations::toString() const
{
    return toJson().toStyledString();
}

Json::Value MediaItemLocalizations::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 7)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getMediaItemId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfMediaItemId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getLanguageId())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfLanguageId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getName())
            {
                ret[pMasqueradingVector[3]]=getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getDescription())
            {
                ret[pMasqueradingVector[4]]=getValueOfDescription();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getTagline())
            {
                ret[pMasqueradingVector[5]]=getValueOfTagline();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getOriginal())
            {
                ret[pMasqueradingVector[6]]=(Json::Int64)getValueOfOriginal();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMediaItemId())
    {
        ret["media_item_id"]=(Json::Int64)getValueOfMediaItemId();
    }
    else
    {
        ret["media_item_id"]=Json::Value();
    }
    if(getLanguageId())
    {
        ret["language_id"]=(Json::Int64)getValueOfLanguageId();
    }
    else
    {
        ret["language_id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getDescription())
    {
        ret["description"]=getValueOfDescription();
    }
    else
    {
        ret["description"]=Json::Value();
    }
    if(getTagline())
    {
        ret["tagline"]=getValueOfTagline();
    }
    else
    {
        ret["tagline"]=Json::Value();
    }
    if(getOriginal())
    {
        ret["original"]=(Json::Int64)getValueOfOriginal();
    }
    else
    {
        ret["original"]=Json::Value();
    }
    return ret;
}

bool MediaItemLocalizations::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("media_item_id"))
    {
        if(!validJsonOfField(1, "media_item_id", pJson["media_item_id"], err, true))
            return false;
    }
    else
    {
        err="The media_item_id column cannot be null";
        return false;
    }
    if(pJson.isMember("language_id"))
    {
        if(!validJsonOfField(2, "language_id", pJson["language_id"], err, true))
            return false;
    }
    else
    {
        err="The language_id column cannot be null";
        return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(3, "name", pJson["name"], err, true))
            return false;
    }
    else
    {
        err="The name column cannot be null";
        return false;
    }
    if(pJson.isMember("description"))
    {
        if(!validJsonOfField(4, "description", pJson["description"], err, true))
            return false;
    }
    else
    {
        err="The description column cannot be null";
        return false;
    }
    if(pJson.isMember("tagline"))
    {
        if(!validJsonOfField(5, "tagline", pJson["tagline"], err, true))
            return false;
    }
    else
    {
        err="The tagline column cannot be null";
        return false;
    }
    if(pJson.isMember("original"))
    {
        if(!validJsonOfField(6, "original", pJson["original"], err, true))
            return false;
    }
    else
    {
        err="The original column cannot be null";
        return false;
    }
    return true;
}
bool MediaItemLocalizations::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                                const std::vector<std::string> &pMasqueradingVector,
                                                                std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[6] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MediaItemLocalizations::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("media_item_id"))
    {
        if(!validJsonOfField(1, "media_item_id", pJson["media_item_id"], err, false))
            return false;
    }
    if(pJson.isMember("language_id"))
    {
        if(!validJsonOfField(2, "language_id", pJson["language_id"], err, false))
            return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(3, "name", pJson["name"], err, false))
            return false;
    }
    if(pJson.isMember("description"))
    {
        if(!validJsonOfField(4, "description", pJson["description"], err, false))
            return false;
    }
    if(pJson.isMember("tagline"))
    {
        if(!validJsonOfField(5, "tagline", pJson["tagline"], err, false))
            return false;
    }
    if(pJson.isMember("original"))
    {
        if(!validJsonOfField(6, "original", pJson["original"], err, false))
            return false;
    }
    return true;
}
bool MediaItemLocalizations::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                              const std::vector<std::string> &pMasqueradingVector,
                                                              std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MediaItemLocalizations::validJsonOfField(size_t index,
                                              const std::string &fieldName,
                                              const Json::Value &pJson,
                                              std::string &err,
                                              bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
