/**
 *
 *  MediaItemTagAssignment.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "MediaItemTagAssignment.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string MediaItemTagAssignment::Cols::_id = "id";
const std::string MediaItemTagAssignment::Cols::_media_item_id = "media_item_id";
const std::string MediaItemTagAssignment::Cols::_tag_id = "tag_id";
const std::string MediaItemTagAssignment::primaryKeyName = "id";
const bool MediaItemTagAssignment::hasPrimaryKey = true;
const std::string MediaItemTagAssignment::tableName = "media_item_tag_assignment";

const std::vector<typename MediaItemTagAssignment::MetaData> MediaItemTagAssignment::metaData_={
{"id","int64_t","integer",8,1,1,1},
{"media_item_id","int64_t","integer",8,0,0,1},
{"tag_id","int64_t","integer",8,0,0,1}
};
const std::string &MediaItemTagAssignment::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
MediaItemTagAssignment::MediaItemTagAssignment(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["media_item_id"].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>(r["media_item_id"].as<int64_t>());
        }
        if(!r["tag_id"].isNull())
        {
            tagId_=std::make_shared<int64_t>(r["tag_id"].as<int64_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            tagId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
    }

}

MediaItemTagAssignment::MediaItemTagAssignment(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            tagId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

MediaItemTagAssignment::MediaItemTagAssignment(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("media_item_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["media_item_id"].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>((int64_t)pJson["media_item_id"].asInt64());
        }
    }
    if(pJson.isMember("tag_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["tag_id"].isNull())
        {
            tagId_=std::make_shared<int64_t>((int64_t)pJson["tag_id"].asInt64());
        }
    }
}

void MediaItemTagAssignment::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            tagId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

void MediaItemTagAssignment::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("media_item_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["media_item_id"].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>((int64_t)pJson["media_item_id"].asInt64());
        }
    }
    if(pJson.isMember("tag_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["tag_id"].isNull())
        {
            tagId_=std::make_shared<int64_t>((int64_t)pJson["tag_id"].asInt64());
        }
    }
}

const int64_t &MediaItemTagAssignment::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MediaItemTagAssignment::getId() const noexcept
{
    return id_;
}
void MediaItemTagAssignment::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename MediaItemTagAssignment::PrimaryKeyType & MediaItemTagAssignment::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &MediaItemTagAssignment::getValueOfMediaItemId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(mediaItemId_)
        return *mediaItemId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MediaItemTagAssignment::getMediaItemId() const noexcept
{
    return mediaItemId_;
}
void MediaItemTagAssignment::setMediaItemId(const int64_t &pMediaItemId) noexcept
{
    mediaItemId_ = std::make_shared<int64_t>(pMediaItemId);
    dirtyFlag_[1] = true;
}

const int64_t &MediaItemTagAssignment::getValueOfTagId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(tagId_)
        return *tagId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MediaItemTagAssignment::getTagId() const noexcept
{
    return tagId_;
}
void MediaItemTagAssignment::setTagId(const int64_t &pTagId) noexcept
{
    tagId_ = std::make_shared<int64_t>(pTagId);
    dirtyFlag_[2] = true;
}

void MediaItemTagAssignment::updateId(const uint64_t id)
{
    id_ = std::make_shared<int64_t>(static_cast<int64_t>(id));
}

const std::vector<std::string> &MediaItemTagAssignment::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "media_item_id",
        "tag_id"
    };
    return inCols;
}

void MediaItemTagAssignment::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMediaItemId())
        {
            binder << getValueOfMediaItemId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTagId())
        {
            binder << getValueOfTagId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> MediaItemTagAssignment::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void MediaItemTagAssignment::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMediaItemId())
        {
            binder << getValueOfMediaItemId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTagId())
        {
            binder << getValueOfTagId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value MediaItemTagAssignment::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMediaItemId())
    {
        ret["media_item_id"]=(Json::Int64)getValueOfMediaItemId();
    }
    else
    {
        ret["media_item_id"]=Json::Value();
    }
    if(getTagId())
    {
        ret["tag_id"]=(Json::Int64)getValueOfTagId();
    }
    else
    {
        ret["tag_id"]=Json::Value();
    }
    return ret;
}

std::string MediaItemTagAssignment::toString() const
{
    return toJson().toStyledString();
}

Json::Value MediaItemTagAssignment::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getMediaItemId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfMediaItemId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getTagId())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfTagId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMediaItemId())
    {
        ret["media_item_id"]=(Json::Int64)getValueOfMediaItemId();
    }
    else
    {
        ret["media_item_id"]=Json::Value();
    }
    if(getTagId())
    {
        ret["tag_id"]=(Json::Int64)getValueOfTagId();
    }
    else
    {
        ret["tag_id"]=Json::Value();
    }
    return ret;
}

bool MediaItemTagAssignment::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("media_item_id"))
    {
        if(!validJsonOfField(1, "media_item_id", pJson["media_item_id"], err, true))
            return false;
    }
    else
    {
        err="The media_item_id column cannot be null";
        return false;
    }
    if(pJson.isMember("tag_id"))
    {
        if(!validJsonOfField(2, "tag_id", pJson["tag_id"], err, true))
            return false;
    }
    else
    {
        err="The tag_id column cannot be null";
        return false;
    }
    return true;
}
bool MediaItemTagAssignment::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                                const std::vector<std::string> &pMasqueradingVector,
                                                                std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MediaItemTagAssignment::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("media_item_id"))
    {
        if(!validJsonOfField(1, "media_item_id", pJson["media_item_id"], err, false))
            return false;
    }
    if(pJson.isMember("tag_id"))
    {
        if(!validJsonOfField(2, "tag_id", pJson["tag_id"], err, false))
            return false;
    }
    return true;
}
bool MediaItemTagAssignment::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                              const std::vector<std::string> &pMasqueradingVector,
                                                              std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MediaItemTagAssignment::validJsonOfField(size_t index,
                                              const std::string &fieldName,
                                              const Json::Value &pJson,
                                              std::string &err,
                                              bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
