/**
 *
 *  People.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "People.h"
#include "ExternalPeopleIds.h"
#include "PeopleLocalizations.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string People::Cols::_id = "id";
const std::string People::Cols::_gender_id = "gender_id";
const std::string People::Cols::_portret_id = "portret_id";
const std::string People::Cols::_date_of_birth = "date_of_birth";
const std::string People::Cols::_date_of_death = "date_of_death";
const std::string People::primaryKeyName = "id";
const bool People::hasPrimaryKey = true;
const std::string People::tableName = "people";

const std::vector<typename People::MetaData> People::metaData_={
{"id","int64_t","integer",8,1,1,1},
{"gender_id","int64_t","integer",8,0,0,1},
{"portret_id","int64_t","integer",8,0,0,0},
{"date_of_birth","std::string","text",0,0,0,1},
{"date_of_death","std::string","text",0,0,0,1}
};
const std::string &People::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
People::People(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["gender_id"].isNull())
        {
            genderId_=std::make_shared<int64_t>(r["gender_id"].as<int64_t>());
        }
        if(!r["portret_id"].isNull())
        {
            portretId_=std::make_shared<int64_t>(r["portret_id"].as<int64_t>());
        }
        if(!r["date_of_birth"].isNull())
        {
            dateOfBirth_=std::make_shared<std::string>(r["date_of_birth"].as<std::string>());
        }
        if(!r["date_of_death"].isNull())
        {
            dateOfDeath_=std::make_shared<std::string>(r["date_of_death"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 5 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            genderId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            portretId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            dateOfBirth_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            dateOfDeath_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

People::People(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            genderId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            portretId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            dateOfBirth_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            dateOfDeath_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
}

People::People(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("gender_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["gender_id"].isNull())
        {
            genderId_=std::make_shared<int64_t>((int64_t)pJson["gender_id"].asInt64());
        }
    }
    if(pJson.isMember("portret_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["portret_id"].isNull())
        {
            portretId_=std::make_shared<int64_t>((int64_t)pJson["portret_id"].asInt64());
        }
    }
    if(pJson.isMember("date_of_birth"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["date_of_birth"].isNull())
        {
            dateOfBirth_=std::make_shared<std::string>(pJson["date_of_birth"].asString());
        }
    }
    if(pJson.isMember("date_of_death"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["date_of_death"].isNull())
        {
            dateOfDeath_=std::make_shared<std::string>(pJson["date_of_death"].asString());
        }
    }
}

void People::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            genderId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            portretId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            dateOfBirth_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            dateOfDeath_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
}

void People::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("gender_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["gender_id"].isNull())
        {
            genderId_=std::make_shared<int64_t>((int64_t)pJson["gender_id"].asInt64());
        }
    }
    if(pJson.isMember("portret_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["portret_id"].isNull())
        {
            portretId_=std::make_shared<int64_t>((int64_t)pJson["portret_id"].asInt64());
        }
    }
    if(pJson.isMember("date_of_birth"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["date_of_birth"].isNull())
        {
            dateOfBirth_=std::make_shared<std::string>(pJson["date_of_birth"].asString());
        }
    }
    if(pJson.isMember("date_of_death"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["date_of_death"].isNull())
        {
            dateOfDeath_=std::make_shared<std::string>(pJson["date_of_death"].asString());
        }
    }
}

const int64_t &People::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &People::getId() const noexcept
{
    return id_;
}
void People::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename People::PrimaryKeyType & People::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &People::getValueOfGenderId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(genderId_)
        return *genderId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &People::getGenderId() const noexcept
{
    return genderId_;
}
void People::setGenderId(const int64_t &pGenderId) noexcept
{
    genderId_ = std::make_shared<int64_t>(pGenderId);
    dirtyFlag_[1] = true;
}

const int64_t &People::getValueOfPortretId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(portretId_)
        return *portretId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &People::getPortretId() const noexcept
{
    return portretId_;
}
void People::setPortretId(const int64_t &pPortretId) noexcept
{
    portretId_ = std::make_shared<int64_t>(pPortretId);
    dirtyFlag_[2] = true;
}
void People::setPortretIdToNull() noexcept
{
    portretId_.reset();
    dirtyFlag_[2] = true;
}

const std::string &People::getValueOfDateOfBirth() const noexcept
{
    static const std::string defaultValue = std::string();
    if(dateOfBirth_)
        return *dateOfBirth_;
    return defaultValue;
}
const std::shared_ptr<std::string> &People::getDateOfBirth() const noexcept
{
    return dateOfBirth_;
}
void People::setDateOfBirth(const std::string &pDateOfBirth) noexcept
{
    dateOfBirth_ = std::make_shared<std::string>(pDateOfBirth);
    dirtyFlag_[3] = true;
}
void People::setDateOfBirth(std::string &&pDateOfBirth) noexcept
{
    dateOfBirth_ = std::make_shared<std::string>(std::move(pDateOfBirth));
    dirtyFlag_[3] = true;
}

const std::string &People::getValueOfDateOfDeath() const noexcept
{
    static const std::string defaultValue = std::string();
    if(dateOfDeath_)
        return *dateOfDeath_;
    return defaultValue;
}
const std::shared_ptr<std::string> &People::getDateOfDeath() const noexcept
{
    return dateOfDeath_;
}
void People::setDateOfDeath(const std::string &pDateOfDeath) noexcept
{
    dateOfDeath_ = std::make_shared<std::string>(pDateOfDeath);
    dirtyFlag_[4] = true;
}
void People::setDateOfDeath(std::string &&pDateOfDeath) noexcept
{
    dateOfDeath_ = std::make_shared<std::string>(std::move(pDateOfDeath));
    dirtyFlag_[4] = true;
}

void People::updateId(const uint64_t id)
{
    id_ = std::make_shared<int64_t>(static_cast<int64_t>(id));
}

const std::vector<std::string> &People::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "gender_id",
        "portret_id",
        "date_of_birth",
        "date_of_death"
    };
    return inCols;
}

void People::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getGenderId())
        {
            binder << getValueOfGenderId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPortretId())
        {
            binder << getValueOfPortretId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDateOfBirth())
        {
            binder << getValueOfDateOfBirth();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getDateOfDeath())
        {
            binder << getValueOfDateOfDeath();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> People::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    return ret;
}

void People::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getGenderId())
        {
            binder << getValueOfGenderId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPortretId())
        {
            binder << getValueOfPortretId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDateOfBirth())
        {
            binder << getValueOfDateOfBirth();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getDateOfDeath())
        {
            binder << getValueOfDateOfDeath();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value People::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getGenderId())
    {
        ret["gender_id"]=(Json::Int64)getValueOfGenderId();
    }
    else
    {
        ret["gender_id"]=Json::Value();
    }
    if(getPortretId())
    {
        ret["portret_id"]=(Json::Int64)getValueOfPortretId();
    }
    else
    {
        ret["portret_id"]=Json::Value();
    }
    if(getDateOfBirth())
    {
        ret["date_of_birth"]=getValueOfDateOfBirth();
    }
    else
    {
        ret["date_of_birth"]=Json::Value();
    }
    if(getDateOfDeath())
    {
        ret["date_of_death"]=getValueOfDateOfDeath();
    }
    else
    {
        ret["date_of_death"]=Json::Value();
    }
    return ret;
}

std::string People::toString() const
{
    return toJson().toStyledString();
}

Json::Value People::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 5)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getGenderId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfGenderId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getPortretId())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfPortretId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getDateOfBirth())
            {
                ret[pMasqueradingVector[3]]=getValueOfDateOfBirth();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getDateOfDeath())
            {
                ret[pMasqueradingVector[4]]=getValueOfDateOfDeath();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getGenderId())
    {
        ret["gender_id"]=(Json::Int64)getValueOfGenderId();
    }
    else
    {
        ret["gender_id"]=Json::Value();
    }
    if(getPortretId())
    {
        ret["portret_id"]=(Json::Int64)getValueOfPortretId();
    }
    else
    {
        ret["portret_id"]=Json::Value();
    }
    if(getDateOfBirth())
    {
        ret["date_of_birth"]=getValueOfDateOfBirth();
    }
    else
    {
        ret["date_of_birth"]=Json::Value();
    }
    if(getDateOfDeath())
    {
        ret["date_of_death"]=getValueOfDateOfDeath();
    }
    else
    {
        ret["date_of_death"]=Json::Value();
    }
    return ret;
}

bool People::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("gender_id"))
    {
        if(!validJsonOfField(1, "gender_id", pJson["gender_id"], err, true))
            return false;
    }
    else
    {
        err="The gender_id column cannot be null";
        return false;
    }
    if(pJson.isMember("portret_id"))
    {
        if(!validJsonOfField(2, "portret_id", pJson["portret_id"], err, true))
            return false;
    }
    if(pJson.isMember("date_of_birth"))
    {
        if(!validJsonOfField(3, "date_of_birth", pJson["date_of_birth"], err, true))
            return false;
    }
    else
    {
        err="The date_of_birth column cannot be null";
        return false;
    }
    if(pJson.isMember("date_of_death"))
    {
        if(!validJsonOfField(4, "date_of_death", pJson["date_of_death"], err, true))
            return false;
    }
    else
    {
        err="The date_of_death column cannot be null";
        return false;
    }
    return true;
}
bool People::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool People::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("gender_id"))
    {
        if(!validJsonOfField(1, "gender_id", pJson["gender_id"], err, false))
            return false;
    }
    if(pJson.isMember("portret_id"))
    {
        if(!validJsonOfField(2, "portret_id", pJson["portret_id"], err, false))
            return false;
    }
    if(pJson.isMember("date_of_birth"))
    {
        if(!validJsonOfField(3, "date_of_birth", pJson["date_of_birth"], err, false))
            return false;
    }
    if(pJson.isMember("date_of_death"))
    {
        if(!validJsonOfField(4, "date_of_death", pJson["date_of_death"], err, false))
            return false;
    }
    return true;
}
bool People::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                              const std::vector<std::string> &pMasqueradingVector,
                                              std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool People::validJsonOfField(size_t index,
                              const std::string &fieldName,
                              const Json::Value &pJson,
                              std::string &err,
                              bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
std::vector<PeopleLocalizations> People::getPeopleLocalizations(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from people_localizations where person_id = ?";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *id_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    std::vector<PeopleLocalizations> ret;
    ret.reserve(r.size());
    for (auto const &row : r)
    {
        ret.emplace_back(PeopleLocalizations(row));
    }
    return ret;
}

void People::getPeopleLocalizations(const DbClientPtr &clientPtr,
                                    const std::function<void(std::vector<PeopleLocalizations>)> &rcb,
                                    const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from people_localizations where person_id = ?";
    *clientPtr << sql
               << *id_
               >> [rcb = std::move(rcb)](const Result &r){
                   std::vector<PeopleLocalizations> ret;
                   ret.reserve(r.size());
                   for (auto const &row : r)
                   {
                       ret.emplace_back(PeopleLocalizations(row));
                   }
                   rcb(ret);
               }
               >> ecb;
}
std::vector<ExternalPeopleIds> People::getExternalPeopleIds(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from external_people_ids where person_id = ?";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *id_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    std::vector<ExternalPeopleIds> ret;
    ret.reserve(r.size());
    for (auto const &row : r)
    {
        ret.emplace_back(ExternalPeopleIds(row));
    }
    return ret;
}

void People::getExternalPeopleIds(const DbClientPtr &clientPtr,
                                  const std::function<void(std::vector<ExternalPeopleIds>)> &rcb,
                                  const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from external_people_ids where person_id = ?";
    *clientPtr << sql
               << *id_
               >> [rcb = std::move(rcb)](const Result &r){
                   std::vector<ExternalPeopleIds> ret;
                   ret.reserve(r.size());
                   for (auto const &row : r)
                   {
                       ret.emplace_back(ExternalPeopleIds(row));
                   }
                   rcb(ret);
               }
               >> ecb;
}
