/**
 *
 *  PeopleLocalizations.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "PeopleLocalizations.h"
#include "People.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string PeopleLocalizations::Cols::_id = "id";
const std::string PeopleLocalizations::Cols::_person_id = "person_id";
const std::string PeopleLocalizations::Cols::_language_id = "language_id";
const std::string PeopleLocalizations::Cols::_name = "name";
const std::string PeopleLocalizations::Cols::_biography = "biography";
const std::string PeopleLocalizations::primaryKeyName = "id";
const bool PeopleLocalizations::hasPrimaryKey = true;
const std::string PeopleLocalizations::tableName = "people_localizations";

const std::vector<typename PeopleLocalizations::MetaData> PeopleLocalizations::metaData_={
{"id","int64_t","integer",8,1,1,1},
{"person_id","int64_t","integer",8,0,0,1},
{"language_id","int64_t","integer",8,0,0,1},
{"name","std::string","text",0,0,0,1},
{"biography","std::string","text",0,0,0,1}
};
const std::string &PeopleLocalizations::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
PeopleLocalizations::PeopleLocalizations(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["person_id"].isNull())
        {
            personId_=std::make_shared<int64_t>(r["person_id"].as<int64_t>());
        }
        if(!r["language_id"].isNull())
        {
            languageId_=std::make_shared<int64_t>(r["language_id"].as<int64_t>());
        }
        if(!r["name"].isNull())
        {
            name_=std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if(!r["biography"].isNull())
        {
            biography_=std::make_shared<std::string>(r["biography"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 5 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            personId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            languageId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            name_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            biography_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

PeopleLocalizations::PeopleLocalizations(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            personId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            languageId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            biography_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
}

PeopleLocalizations::PeopleLocalizations(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("person_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["person_id"].isNull())
        {
            personId_=std::make_shared<int64_t>((int64_t)pJson["person_id"].asInt64());
        }
    }
    if(pJson.isMember("language_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["language_id"].isNull())
        {
            languageId_=std::make_shared<int64_t>((int64_t)pJson["language_id"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("biography"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["biography"].isNull())
        {
            biography_=std::make_shared<std::string>(pJson["biography"].asString());
        }
    }
}

void PeopleLocalizations::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            personId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            languageId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            biography_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
}

void PeopleLocalizations::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("person_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["person_id"].isNull())
        {
            personId_=std::make_shared<int64_t>((int64_t)pJson["person_id"].asInt64());
        }
    }
    if(pJson.isMember("language_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["language_id"].isNull())
        {
            languageId_=std::make_shared<int64_t>((int64_t)pJson["language_id"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("biography"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["biography"].isNull())
        {
            biography_=std::make_shared<std::string>(pJson["biography"].asString());
        }
    }
}

const int64_t &PeopleLocalizations::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &PeopleLocalizations::getId() const noexcept
{
    return id_;
}
void PeopleLocalizations::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename PeopleLocalizations::PrimaryKeyType & PeopleLocalizations::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &PeopleLocalizations::getValueOfPersonId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(personId_)
        return *personId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &PeopleLocalizations::getPersonId() const noexcept
{
    return personId_;
}
void PeopleLocalizations::setPersonId(const int64_t &pPersonId) noexcept
{
    personId_ = std::make_shared<int64_t>(pPersonId);
    dirtyFlag_[1] = true;
}

const int64_t &PeopleLocalizations::getValueOfLanguageId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(languageId_)
        return *languageId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &PeopleLocalizations::getLanguageId() const noexcept
{
    return languageId_;
}
void PeopleLocalizations::setLanguageId(const int64_t &pLanguageId) noexcept
{
    languageId_ = std::make_shared<int64_t>(pLanguageId);
    dirtyFlag_[2] = true;
}

const std::string &PeopleLocalizations::getValueOfName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PeopleLocalizations::getName() const noexcept
{
    return name_;
}
void PeopleLocalizations::setName(const std::string &pName) noexcept
{
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[3] = true;
}
void PeopleLocalizations::setName(std::string &&pName) noexcept
{
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[3] = true;
}

const std::string &PeopleLocalizations::getValueOfBiography() const noexcept
{
    static const std::string defaultValue = std::string();
    if(biography_)
        return *biography_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PeopleLocalizations::getBiography() const noexcept
{
    return biography_;
}
void PeopleLocalizations::setBiography(const std::string &pBiography) noexcept
{
    biography_ = std::make_shared<std::string>(pBiography);
    dirtyFlag_[4] = true;
}
void PeopleLocalizations::setBiography(std::string &&pBiography) noexcept
{
    biography_ = std::make_shared<std::string>(std::move(pBiography));
    dirtyFlag_[4] = true;
}

void PeopleLocalizations::updateId(const uint64_t id)
{
    id_ = std::make_shared<int64_t>(static_cast<int64_t>(id));
}

const std::vector<std::string> &PeopleLocalizations::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "person_id",
        "language_id",
        "name",
        "biography"
    };
    return inCols;
}

void PeopleLocalizations::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getPersonId())
        {
            binder << getValueOfPersonId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getLanguageId())
        {
            binder << getValueOfLanguageId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getBiography())
        {
            binder << getValueOfBiography();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> PeopleLocalizations::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    return ret;
}

void PeopleLocalizations::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getPersonId())
        {
            binder << getValueOfPersonId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getLanguageId())
        {
            binder << getValueOfLanguageId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getBiography())
        {
            binder << getValueOfBiography();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value PeopleLocalizations::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getPersonId())
    {
        ret["person_id"]=(Json::Int64)getValueOfPersonId();
    }
    else
    {
        ret["person_id"]=Json::Value();
    }
    if(getLanguageId())
    {
        ret["language_id"]=(Json::Int64)getValueOfLanguageId();
    }
    else
    {
        ret["language_id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getBiography())
    {
        ret["biography"]=getValueOfBiography();
    }
    else
    {
        ret["biography"]=Json::Value();
    }
    return ret;
}

std::string PeopleLocalizations::toString() const
{
    return toJson().toStyledString();
}

Json::Value PeopleLocalizations::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 5)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getPersonId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfPersonId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getLanguageId())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfLanguageId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getName())
            {
                ret[pMasqueradingVector[3]]=getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getBiography())
            {
                ret[pMasqueradingVector[4]]=getValueOfBiography();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getPersonId())
    {
        ret["person_id"]=(Json::Int64)getValueOfPersonId();
    }
    else
    {
        ret["person_id"]=Json::Value();
    }
    if(getLanguageId())
    {
        ret["language_id"]=(Json::Int64)getValueOfLanguageId();
    }
    else
    {
        ret["language_id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getBiography())
    {
        ret["biography"]=getValueOfBiography();
    }
    else
    {
        ret["biography"]=Json::Value();
    }
    return ret;
}

bool PeopleLocalizations::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("person_id"))
    {
        if(!validJsonOfField(1, "person_id", pJson["person_id"], err, true))
            return false;
    }
    else
    {
        err="The person_id column cannot be null";
        return false;
    }
    if(pJson.isMember("language_id"))
    {
        if(!validJsonOfField(2, "language_id", pJson["language_id"], err, true))
            return false;
    }
    else
    {
        err="The language_id column cannot be null";
        return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(3, "name", pJson["name"], err, true))
            return false;
    }
    else
    {
        err="The name column cannot be null";
        return false;
    }
    if(pJson.isMember("biography"))
    {
        if(!validJsonOfField(4, "biography", pJson["biography"], err, true))
            return false;
    }
    else
    {
        err="The biography column cannot be null";
        return false;
    }
    return true;
}
bool PeopleLocalizations::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                             const std::vector<std::string> &pMasqueradingVector,
                                                             std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PeopleLocalizations::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("person_id"))
    {
        if(!validJsonOfField(1, "person_id", pJson["person_id"], err, false))
            return false;
    }
    if(pJson.isMember("language_id"))
    {
        if(!validJsonOfField(2, "language_id", pJson["language_id"], err, false))
            return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(3, "name", pJson["name"], err, false))
            return false;
    }
    if(pJson.isMember("biography"))
    {
        if(!validJsonOfField(4, "biography", pJson["biography"], err, false))
            return false;
    }
    return true;
}
bool PeopleLocalizations::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                           const std::vector<std::string> &pMasqueradingVector,
                                                           std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PeopleLocalizations::validJsonOfField(size_t index,
                                           const std::string &fieldName,
                                           const Json::Value &pJson,
                                           std::string &err,
                                           bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
People PeopleLocalizations::getPeople(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from people where id = ?";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *personId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return People(r[0]);
}

void PeopleLocalizations::getPeople(const DbClientPtr &clientPtr,
                                    const std::function<void(People)> &rcb,
                                    const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from people where id = ?";
    *clientPtr << sql
               << *personId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(People(r[0]));
                    }
               }
               >> ecb;
}
