/**
 *
 *  ServerSettings.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "ServerSettings.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string ServerSettings::Cols::_id = "id";
const std::string ServerSettings::Cols::_setting_name = "setting_name";
const std::string ServerSettings::Cols::_value = "value";
const std::string ServerSettings::primaryKeyName = "id";
const bool ServerSettings::hasPrimaryKey = true;
const std::string ServerSettings::tableName = "server_settings";

const std::vector<typename ServerSettings::MetaData> ServerSettings::metaData_={
{"id","int64_t","integer",8,1,1,1},
{"setting_name","std::string","text",0,0,0,1},
{"value","std::string","any",0,0,0,1}
};
const std::string &ServerSettings::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
ServerSettings::ServerSettings(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["setting_name"].isNull())
        {
            settingName_=std::make_shared<std::string>(r["setting_name"].as<std::string>());
        }
        if(!r["value"].isNull())
        {
            value_=std::make_shared<std::string>(r["value"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            settingName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            value_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

ServerSettings::ServerSettings(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            settingName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            value_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

ServerSettings::ServerSettings(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("setting_name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["setting_name"].isNull())
        {
            settingName_=std::make_shared<std::string>(pJson["setting_name"].asString());
        }
    }
    if(pJson.isMember("value"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["value"].isNull())
        {
            value_=std::make_shared<std::string>(pJson["value"].asString());
        }
    }
}

void ServerSettings::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            settingName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            value_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

void ServerSettings::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("setting_name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["setting_name"].isNull())
        {
            settingName_=std::make_shared<std::string>(pJson["setting_name"].asString());
        }
    }
    if(pJson.isMember("value"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["value"].isNull())
        {
            value_=std::make_shared<std::string>(pJson["value"].asString());
        }
    }
}

const int64_t &ServerSettings::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &ServerSettings::getId() const noexcept
{
    return id_;
}
void ServerSettings::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename ServerSettings::PrimaryKeyType & ServerSettings::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &ServerSettings::getValueOfSettingName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(settingName_)
        return *settingName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ServerSettings::getSettingName() const noexcept
{
    return settingName_;
}
void ServerSettings::setSettingName(const std::string &pSettingName) noexcept
{
    settingName_ = std::make_shared<std::string>(pSettingName);
    dirtyFlag_[1] = true;
}
void ServerSettings::setSettingName(std::string &&pSettingName) noexcept
{
    settingName_ = std::make_shared<std::string>(std::move(pSettingName));
    dirtyFlag_[1] = true;
}

const std::string &ServerSettings::getValueOfValue() const noexcept
{
    static const std::string defaultValue = std::string();
    if(value_)
        return *value_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ServerSettings::getValue() const noexcept
{
    return value_;
}
void ServerSettings::setValue(const std::string &pValue) noexcept
{
    value_ = std::make_shared<std::string>(pValue);
    dirtyFlag_[2] = true;
}
void ServerSettings::setValue(std::string &&pValue) noexcept
{
    value_ = std::make_shared<std::string>(std::move(pValue));
    dirtyFlag_[2] = true;
}

void ServerSettings::updateId(const uint64_t id)
{
    id_ = std::make_shared<int64_t>(static_cast<int64_t>(id));
}

const std::vector<std::string> &ServerSettings::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "setting_name",
        "value"
    };
    return inCols;
}

void ServerSettings::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getSettingName())
        {
            binder << getValueOfSettingName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getValue())
        {
            binder << getValueOfValue();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> ServerSettings::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void ServerSettings::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getSettingName())
        {
            binder << getValueOfSettingName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getValue())
        {
            binder << getValueOfValue();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value ServerSettings::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getSettingName())
    {
        ret["setting_name"]=getValueOfSettingName();
    }
    else
    {
        ret["setting_name"]=Json::Value();
    }
    if(getValue())
    {
        ret["value"]=getValueOfValue();
    }
    else
    {
        ret["value"]=Json::Value();
    }
    return ret;
}

std::string ServerSettings::toString() const
{
    return toJson().toStyledString();
}

Json::Value ServerSettings::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getSettingName())
            {
                ret[pMasqueradingVector[1]]=getValueOfSettingName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getValue())
            {
                ret[pMasqueradingVector[2]]=getValueOfValue();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getSettingName())
    {
        ret["setting_name"]=getValueOfSettingName();
    }
    else
    {
        ret["setting_name"]=Json::Value();
    }
    if(getValue())
    {
        ret["value"]=getValueOfValue();
    }
    else
    {
        ret["value"]=Json::Value();
    }
    return ret;
}

bool ServerSettings::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("setting_name"))
    {
        if(!validJsonOfField(1, "setting_name", pJson["setting_name"], err, true))
            return false;
    }
    else
    {
        err="The setting_name column cannot be null";
        return false;
    }
    if(pJson.isMember("value"))
    {
        if(!validJsonOfField(2, "value", pJson["value"], err, true))
            return false;
    }
    else
    {
        err="The value column cannot be null";
        return false;
    }
    return true;
}
bool ServerSettings::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                        const std::vector<std::string> &pMasqueradingVector,
                                                        std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ServerSettings::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("setting_name"))
    {
        if(!validJsonOfField(1, "setting_name", pJson["setting_name"], err, false))
            return false;
    }
    if(pJson.isMember("value"))
    {
        if(!validJsonOfField(2, "value", pJson["value"], err, false))
            return false;
    }
    return true;
}
bool ServerSettings::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ServerSettings::validJsonOfField(size_t index,
                                      const std::string &fieldName,
                                      const Json::Value &pJson,
                                      std::string &err,
                                      bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
