/**
 *
 *  VideoTracks.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "VideoTracks.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string VideoTracks::Cols::_id = "id";
const std::string VideoTracks::Cols::_media_item_id = "media_item_id";
const std::string VideoTracks::Cols::_width = "width";
const std::string VideoTracks::Cols::_height = "height";
const std::string VideoTracks::primaryKeyName = "id";
const bool VideoTracks::hasPrimaryKey = true;
const std::string VideoTracks::tableName = "video_tracks";

const std::vector<typename VideoTracks::MetaData> VideoTracks::metaData_={
{"id","int64_t","integer",8,1,1,1},
{"media_item_id","int64_t","integer",8,0,0,1},
{"width","int64_t","integer",8,0,0,1},
{"height","int64_t","integer",8,0,0,1}
};
const std::string &VideoTracks::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
VideoTracks::VideoTracks(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["media_item_id"].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>(r["media_item_id"].as<int64_t>());
        }
        if(!r["width"].isNull())
        {
            width_=std::make_shared<int64_t>(r["width"].as<int64_t>());
        }
        if(!r["height"].isNull())
        {
            height_=std::make_shared<int64_t>(r["height"].as<int64_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            width_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            height_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
    }

}

VideoTracks::VideoTracks(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            width_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            height_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
}

VideoTracks::VideoTracks(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("media_item_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["media_item_id"].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>((int64_t)pJson["media_item_id"].asInt64());
        }
    }
    if(pJson.isMember("width"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["width"].isNull())
        {
            width_=std::make_shared<int64_t>((int64_t)pJson["width"].asInt64());
        }
    }
    if(pJson.isMember("height"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["height"].isNull())
        {
            height_=std::make_shared<int64_t>((int64_t)pJson["height"].asInt64());
        }
    }
}

void VideoTracks::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            width_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            height_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
}

void VideoTracks::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("media_item_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["media_item_id"].isNull())
        {
            mediaItemId_=std::make_shared<int64_t>((int64_t)pJson["media_item_id"].asInt64());
        }
    }
    if(pJson.isMember("width"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["width"].isNull())
        {
            width_=std::make_shared<int64_t>((int64_t)pJson["width"].asInt64());
        }
    }
    if(pJson.isMember("height"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["height"].isNull())
        {
            height_=std::make_shared<int64_t>((int64_t)pJson["height"].asInt64());
        }
    }
}

const int64_t &VideoTracks::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &VideoTracks::getId() const noexcept
{
    return id_;
}
void VideoTracks::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename VideoTracks::PrimaryKeyType & VideoTracks::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &VideoTracks::getValueOfMediaItemId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(mediaItemId_)
        return *mediaItemId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &VideoTracks::getMediaItemId() const noexcept
{
    return mediaItemId_;
}
void VideoTracks::setMediaItemId(const int64_t &pMediaItemId) noexcept
{
    mediaItemId_ = std::make_shared<int64_t>(pMediaItemId);
    dirtyFlag_[1] = true;
}

const int64_t &VideoTracks::getValueOfWidth() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(width_)
        return *width_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &VideoTracks::getWidth() const noexcept
{
    return width_;
}
void VideoTracks::setWidth(const int64_t &pWidth) noexcept
{
    width_ = std::make_shared<int64_t>(pWidth);
    dirtyFlag_[2] = true;
}

const int64_t &VideoTracks::getValueOfHeight() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(height_)
        return *height_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &VideoTracks::getHeight() const noexcept
{
    return height_;
}
void VideoTracks::setHeight(const int64_t &pHeight) noexcept
{
    height_ = std::make_shared<int64_t>(pHeight);
    dirtyFlag_[3] = true;
}

void VideoTracks::updateId(const uint64_t id)
{
    id_ = std::make_shared<int64_t>(static_cast<int64_t>(id));
}

const std::vector<std::string> &VideoTracks::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "media_item_id",
        "width",
        "height"
    };
    return inCols;
}

void VideoTracks::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMediaItemId())
        {
            binder << getValueOfMediaItemId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getWidth())
        {
            binder << getValueOfWidth();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getHeight())
        {
            binder << getValueOfHeight();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> VideoTracks::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void VideoTracks::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMediaItemId())
        {
            binder << getValueOfMediaItemId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getWidth())
        {
            binder << getValueOfWidth();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getHeight())
        {
            binder << getValueOfHeight();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value VideoTracks::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMediaItemId())
    {
        ret["media_item_id"]=(Json::Int64)getValueOfMediaItemId();
    }
    else
    {
        ret["media_item_id"]=Json::Value();
    }
    if(getWidth())
    {
        ret["width"]=(Json::Int64)getValueOfWidth();
    }
    else
    {
        ret["width"]=Json::Value();
    }
    if(getHeight())
    {
        ret["height"]=(Json::Int64)getValueOfHeight();
    }
    else
    {
        ret["height"]=Json::Value();
    }
    return ret;
}

Json::Value VideoTracks::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getMediaItemId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfMediaItemId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getWidth())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfWidth();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getHeight())
            {
                ret[pMasqueradingVector[3]]=(Json::Int64)getValueOfHeight();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMediaItemId())
    {
        ret["media_item_id"]=(Json::Int64)getValueOfMediaItemId();
    }
    else
    {
        ret["media_item_id"]=Json::Value();
    }
    if(getWidth())
    {
        ret["width"]=(Json::Int64)getValueOfWidth();
    }
    else
    {
        ret["width"]=Json::Value();
    }
    if(getHeight())
    {
        ret["height"]=(Json::Int64)getValueOfHeight();
    }
    else
    {
        ret["height"]=Json::Value();
    }
    return ret;
}

bool VideoTracks::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("media_item_id"))
    {
        if(!validJsonOfField(1, "media_item_id", pJson["media_item_id"], err, true))
            return false;
    }
    else
    {
        err="The media_item_id column cannot be null";
        return false;
    }
    if(pJson.isMember("width"))
    {
        if(!validJsonOfField(2, "width", pJson["width"], err, true))
            return false;
    }
    else
    {
        err="The width column cannot be null";
        return false;
    }
    if(pJson.isMember("height"))
    {
        if(!validJsonOfField(3, "height", pJson["height"], err, true))
            return false;
    }
    else
    {
        err="The height column cannot be null";
        return false;
    }
    return true;
}
bool VideoTracks::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool VideoTracks::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("media_item_id"))
    {
        if(!validJsonOfField(1, "media_item_id", pJson["media_item_id"], err, false))
            return false;
    }
    if(pJson.isMember("width"))
    {
        if(!validJsonOfField(2, "width", pJson["width"], err, false))
            return false;
    }
    if(pJson.isMember("height"))
    {
        if(!validJsonOfField(3, "height", pJson["height"], err, false))
            return false;
    }
    return true;
}
bool VideoTracks::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool VideoTracks::validJsonOfField(size_t index,
                                   const std::string &fieldName,
                                   const Json::Value &pJson,
                                   std::string &err,
                                   bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
